-- DATA-001: relational catalogue, ownership, wallets, materials and condition.
-- Character blobs remain in place during the compatibility/backfill period.

-- Live Supabase already had these prototype catalogues. Define them here as
-- well so a brand-new or restored database can run the full migration chain.
CREATE TABLE IF NOT EXISTS weapons (
  id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '',
  value NUMERIC NOT NULL DEFAULT 0 CHECK (value >= 0),
  weight NUMERIC NOT NULL DEFAULT 0 CHECK (weight >= 0),
  default_quantity INTEGER NOT NULL DEFAULT 1 CHECK (default_quantity >= 0),
  stat TEXT NOT NULL DEFAULT 'str' CHECK (stat IN ('str','dex','con','int','bld_str','cha')),
  advantage TEXT NOT NULL DEFAULT 'Normal', to_hit_bonus INTEGER NOT NULL DEFAULT 0,
  damage_1 TEXT NOT NULL DEFAULT '1d4', damage_type_1 TEXT NOT NULL DEFAULT 'Other',
  damage_2 TEXT, damage_type_2 TEXT, proficient BOOLEAN NOT NULL DEFAULT TRUE,
  pools TEXT[] NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS armour (
  id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '',
  value NUMERIC NOT NULL DEFAULT 0 CHECK (value >= 0),
  weight NUMERIC NOT NULL DEFAULT 0 CHECK (weight >= 0),
  default_quantity INTEGER NOT NULL DEFAULT 1 CHECK (default_quantity >= 0),
  base_ac INTEGER NOT NULL DEFAULT 10,
  armour_type TEXT NOT NULL DEFAULT 'Light' CHECK (armour_type IN ('Light','Medium','Heavy','Shield','Unarmoured')),
  max_dex_bonus INTEGER NOT NULL DEFAULT 0, proficient BOOLEAN NOT NULL DEFAULT TRUE,
  pools TEXT[] NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS items (
  id TEXT PRIMARY KEY, name TEXT NOT NULL, item_type TEXT NOT NULL DEFAULT 'item',
  description TEXT NOT NULL DEFAULT '', value NUMERIC NOT NULL DEFAULT 0 CHECK (value >= 0),
  weight NUMERIC NOT NULL DEFAULT 0 CHECK (weight >= 0),
  default_quantity INTEGER NOT NULL DEFAULT 1 CHECK (default_quantity >= 0),
  effect TEXT, effect_amount TEXT, pools TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS item_materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  cost_modifier DOUBLE PRECISION NOT NULL DEFAULT 0,
  weight_modifier DOUBLE PRECISION NOT NULL DEFAULT 0,
  attack_bonus REAL NOT NULL DEFAULT 0,
  damage_modifier REAL NOT NULL DEFAULT 0,
  light_armour_modifier REAL NOT NULL DEFAULT 0,
  medium_armour_modifier REAL NOT NULL DEFAULT 0,
  heavy_armour_modifier REAL NOT NULL DEFAULT 0,
  medium_armour_stealth TEXT,
  heavy_armour_stealth TEXT,
  heavy_armour_strength_req REAL,
  is_iron BOOLEAN NOT NULL DEFAULT FALSE,
  drop_rate DOUBLE PRECISION,
  pool_restrict TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $migration$
BEGIN
  IF to_regclass('public."Materials"') IS NOT NULL THEN
    EXECUTE $copy$
      INSERT INTO item_materials (
        id, name, cost_modifier, weight_modifier, attack_bonus, damage_modifier,
        light_armour_modifier, medium_armour_modifier, heavy_armour_modifier,
        medium_armour_stealth, heavy_armour_stealth, heavy_armour_strength_req,
        is_iron, drop_rate, pool_restrict, created_at
      )
      SELECT id, COALESCE(NULLIF(trim("Name"), ''), 'Material ' || id),
        COALESCE(cost_modifier, 0), COALESCE(weight_modifier, 0),
        COALESCE(attack_bonus, 0), COALESCE(damage_modifier, 0),
        COALESCE(light_armour_modifier, 0), COALESCE(medium_armour_modifier, 0),
        COALESCE(heavy_armour_modifier, 0), medium_armour_stealth,
        heavy_armour_stealth, heavy_armour_strength_req, COALESCE(is_iron, FALSE),
        drop_rate, pool_restrict, created_at FROM "Materials"
      ON CONFLICT (id) DO NOTHING
    $copy$;
  END IF;
END $migration$;

SELECT setval(
  pg_get_serial_sequence('item_materials', 'id'),
  GREATEST(COALESCE((SELECT max(id) FROM item_materials), 0), 1),
  EXISTS (SELECT 1 FROM item_materials)
);

CREATE TABLE IF NOT EXISTS item_conditions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  cost_modifier DOUBLE PRECISION NOT NULL DEFAULT 0,
  attack_bonus REAL NOT NULL DEFAULT 0,
  damage_modifier REAL NOT NULL DEFAULT 0,
  armour_modifier REAL NOT NULL DEFAULT 0,
  drop_rate DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $migration$
BEGIN
  IF to_regclass('public."Condition"') IS NOT NULL THEN
    EXECUTE $copy$
      INSERT INTO item_conditions (
        id, name, cost_modifier, attack_bonus, damage_modifier, armour_modifier,
        drop_rate, created_at
      )
      SELECT id, COALESCE(NULLIF(trim("Name"), ''), 'Condition ' || id),
        COALESCE(cost_modifier, 0), COALESCE(attack_bonus, 0),
        COALESCE(damage_modifier, 0), COALESCE(armour_modifier, 0),
        drop_rate, created_at FROM "Condition"
      ON CONFLICT (id) DO NOTHING
    $copy$;
  END IF;
END $migration$;

SELECT setval(
  pg_get_serial_sequence('item_conditions', 'id'),
  GREATEST(COALESCE((SELECT max(id) FROM item_conditions), 0), 1),
  EXISTS (SELECT 1 FROM item_conditions)
);

ALTER TABLE weapons
  ADD COLUMN IF NOT EXISTS default_material_id BIGINT REFERENCES item_materials(id),
  ADD COLUMN IF NOT EXISTS default_condition_id BIGINT REFERENCES item_conditions(id);

ALTER TABLE armour
  ADD COLUMN IF NOT EXISTS default_material_id BIGINT REFERENCES item_materials(id),
  ADD COLUMN IF NOT EXISTS default_condition_id BIGINT REFERENCES item_conditions(id);

ALTER TABLE items
  ADD COLUMN IF NOT EXISTS default_material_id BIGINT REFERENCES item_materials(id),
  ADD COLUMN IF NOT EXISTS default_condition_id BIGINT REFERENCES item_conditions(id);

DO $migration$
DECLARE character_id_type TEXT;
BEGIN
  SELECT format_type(a.atttypid, a.atttypmod) INTO character_id_type
  FROM pg_attribute a WHERE a.attrelid='character_blobs'::regclass AND a.attname='id';
  EXECUTE format($sql$
    CREATE TABLE IF NOT EXISTS character_wallets (
      character_id %s PRIMARY KEY REFERENCES character_blobs(id) ON DELETE CASCADE,
      gold NUMERIC NOT NULL DEFAULT 0 CHECK (gold >= 0),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  $sql$, character_id_type);
  EXECUTE format($sql$
    CREATE TABLE IF NOT EXISTS character_inventory_items (
  character_id %s NOT NULL REFERENCES character_blobs(id) ON DELETE CASCADE,
  instance_id TEXT NOT NULL,
  weapon_id TEXT REFERENCES weapons(id) ON UPDATE CASCADE,
  armour_id TEXT REFERENCES armour(id) ON UPDATE CASCADE,
  item_id TEXT REFERENCES items(id) ON UPDATE CASCADE,
  quantity NUMERIC NOT NULL DEFAULT 1 CHECK (quantity >= 0),
  equipped BOOLEAN NOT NULL DEFAULT FALSE,
  in_bag BOOLEAN NOT NULL DEFAULT FALSE,
  material_id BIGINT REFERENCES item_materials(id),
  condition_id BIGINT REFERENCES item_conditions(id),
  custom_name TEXT,
  custom_description TEXT,
  custom_value NUMERIC,
  custom_weight NUMERIC,
  properties JSONB NOT NULL DEFAULT '{}'::jsonb,
  source TEXT NOT NULL DEFAULT 'character_backfill',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (character_id, instance_id),
  CONSTRAINT character_inventory_one_definition CHECK (
    (weapon_id IS NOT NULL)::INTEGER +
    (armour_id IS NOT NULL)::INTEGER +
    (item_id IS NOT NULL)::INTEGER = 1
  )
    )
  $sql$, character_id_type);
END $migration$;

CREATE INDEX IF NOT EXISTS character_inventory_character_idx
  ON character_inventory_items(character_id);
CREATE INDEX IF NOT EXISTS character_inventory_weapon_idx
  ON character_inventory_items(weapon_id) WHERE weapon_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS character_inventory_armour_idx
  ON character_inventory_items(armour_id) WHERE armour_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS character_inventory_item_idx
  ON character_inventory_items(item_id) WHERE item_id IS NOT NULL;

-- A rule belongs either to a named NPC pool or to an additive characteristic.
-- Three nullable definition columns retain real foreign keys without a weak
-- polymorphic item reference.
CREATE TABLE IF NOT EXISTS inventory_pool_rules (
  id BIGSERIAL PRIMARY KEY,
  owner_type TEXT NOT NULL CHECK (owner_type IN ('pool', 'characteristic')),
  owner_key TEXT NOT NULL,
  weapon_id TEXT REFERENCES weapons(id) ON UPDATE CASCADE ON DELETE CASCADE,
  armour_id TEXT REFERENCES armour(id) ON UPDATE CASCADE ON DELETE CASCADE,
  item_id TEXT REFERENCES items(id) ON UPDATE CASCADE ON DELETE CASCADE,
  chance NUMERIC NOT NULL DEFAULT 100 CHECK (chance >= 0 AND chance <= 100),
  alternative_group TEXT,
  group_required BOOLEAN NOT NULL DEFAULT FALSE,
  min_quantity INTEGER NOT NULL DEFAULT 1 CHECK (min_quantity >= 0),
  max_quantity INTEGER NOT NULL DEFAULT 1 CHECK (max_quantity >= min_quantity),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT inventory_pool_rule_one_definition CHECK (
    (weapon_id IS NOT NULL)::INTEGER +
    (armour_id IS NOT NULL)::INTEGER +
    (item_id IS NOT NULL)::INTEGER = 1
  ),
  UNIQUE NULLS NOT DISTINCT (
    owner_type, owner_key, weapon_id, armour_id, item_id, alternative_group
  )
);

CREATE INDEX IF NOT EXISTS inventory_pool_rules_owner_idx
  ON inventory_pool_rules(owner_type, lower(owner_key));
