BEGIN;

WITH mundane(id,name,description,value,weight) AS (VALUES
('mundane_001','Bedroll','A wool-lined travelling bedroll with leather ties.',1,7),
('mundane_002','Blanket','A thick woven blanket suitable for cold nights.',1,3),
('mundane_003','Canvas Tent','A two-person canvas tent with pegs and poles.',10,20),
('mundane_004','Hemp Rope (50 ft)','Fifty feet of dependable hemp rope.',1,10),
('mundane_005','Silk Rope (50 ft)','Light, strong rope favoured by climbers.',10,5),
('mundane_006','Grappling Hook','A four-pronged iron climbing hook.',2,4),
('mundane_007','Wooden Ladder','A sturdy ten-foot ladder.',1,25),
('mundane_008','Iron Chain (10 ft)','Ten feet of heavy iron chain.',5,10),
('mundane_009','Iron Padlock','A simple keyed iron lock.',10,1),
('mundane_010','Manacles','Iron restraints with a small key.',2,6),
('mundane_011','Backpack','A leather pack with straps and outer pockets.',2,5),
('mundane_012','Belt Pouch','A small buckled purse worn at the waist.',1,1),
('mundane_013','Canvas Sack','A rough sack holding up to thirty pounds.',0.1,0.5),
('mundane_014','Wooden Chest','A lockable travel chest with iron corners.',5,25),
('mundane_015','Glass Bottle','A stoppered clear glass bottle.',2,2),
('mundane_016','Clay Jug','A glazed jug holding about a gallon.',0.2,4),
('mundane_017','Waterskin','A stitched leather waterskin.',0.2,5),
('mundane_018','Iron Flask','A durable half-pint flask.',0.1,1),
('mundane_019','Small Barrel','A coopered barrel suitable for drink or provisions.',2,20),
('mundane_020','Wicker Basket','A handled basket for gathered goods.',0.4,2),
('mundane_021','Hooded Lantern','A shuttered lantern with directional light.',5,2),
('mundane_022','Bullseye Lantern','A focused lantern visible at long distance.',10,2),
('mundane_023','Common Lamp','A small oil-burning table lamp.',0.5,1),
('mundane_024','Tallow Candle','A single smoky candle lasting about an hour.',0.01,0),
('mundane_025','Tinderbox','Flint, steel and dry tinder in a tin.',0.5,1),
('mundane_026','Lamp Oil Flask','A clay flask of lamp oil.',0.1,1),
('mundane_027','Bundle of Torches','Five resin-soaked wooden torches.',0.05,5),
('mundane_028','Signal Whistle','A shrill brass whistle.',0.05,0),
('mundane_029','Hand Bell','A small brass hand bell.',1,1),
('mundane_030','Steel Mirror','A polished palm-sized steel mirror.',5,0.5),
('mundane_031','Crowbar','An iron bar useful for leverage.',2,5),
('mundane_032','Small Hammer','A compact iron-headed hammer.',1,3),
('mundane_033','Sledgehammer','A heavy two-handed work hammer.',2,10),
('mundane_034','Iron Spikes (10)','Ten square iron spikes.',1,5),
('mundane_035','Wooden Pitons (10)','Ten hardwood climbing pegs.',0.5,2),
('mundane_036','Shovel','A wooden-handled iron shovel.',2,5),
('mundane_037','Pickaxe','A miner''s iron pick.',2,10),
('mundane_038','Wood Axe','A practical axe for splitting timber.',1,5),
('mundane_039','Handsaw','A toothed carpenter''s saw.',1,2),
('mundane_040','Iron Tongs','Long iron smithing tongs.',0.5,2),
('mundane_041','Needle and Thread','Steel needles with strong linen thread.',0.1,0),
('mundane_042','Fishing Tackle','Hooks, line, cork floats and lead weights.',1,4),
('mundane_043','Hunting Trap','A toothed iron jaw trap with chain.',5,25),
('mundane_044','Animal Snare','Wire, cord and pegs for a small-game snare.',0.5,2),
('mundane_045','Mess Kit','Tin plate, cup and folding utensils.',0.2,1),
('mundane_046','Iron Cooking Pot','A lidded camp pot with hanging handle.',2,10),
('mundane_047','Frying Pan','A shallow iron cooking pan.',1,5),
('mundane_048','Wooden Spoon','A plain carved cooking spoon.',0.02,0),
('mundane_049','Butcher Knife','A broad kitchen knife intended for food preparation.',1,1),
('mundane_050','Mortar and Pestle','A stone bowl and grinder for herbs.',1,3),
('mundane_051','Chalk Pieces (10)','Ten sticks of white marking chalk.',0.1,0),
('mundane_052','Charcoal Sticks (10)','Ten wrapped drawing and marking sticks.',0.1,0),
('mundane_053','Ink Bottle','A one-ounce bottle of black writing ink.',10,0),
('mundane_054','Ink Pen','A sharpened quill and spare nib.',0.02,0),
('mundane_055','Parchment Sheets (10)','Ten prepared sheets for writing.',1,0),
('mundane_056','Blank Journal','A stitched book of rough blank pages.',5,3),
('mundane_057','Sealing Wax','A stick of red wax for letters.',0.5,0),
('mundane_058','Map Case','A waterproofed leather scroll tube.',1,1),
('mundane_059','Abacus','A wooden counting frame.',2,2),
('mundane_060','Magnifying Lens','A small ground-glass reading lens.',100,0),
('mundane_061','Hourglass','A one-hour glass timer in a wooden frame.',25,1),
('mundane_062','Compass','A magnetised needle in a brass case.',25,0.5),
('mundane_063','Measuring Cord','A knotted fifty-foot surveyor''s cord.',0.5,2),
('mundane_064','Merchant Scales','A small balance with brass weights.',5,3),
('mundane_065','Common Clothes','A shirt, trousers, belt and simple shoes.',0.5,3),
('mundane_066','Traveller Clothes','Hard-wearing layers, cloak and boots.',2,4),
('mundane_067','Fine Clothes','Tailored garments with decorative trim.',15,6),
('mundane_068','Winter Cloak','A heavy wool cloak lined with fur scraps.',5,6),
('mundane_069','Rain Cape','An oiled canvas hooded cape.',2,4),
('mundane_070','Leather Gloves','Hard-wearing work gloves.',0.5,0.5),
('mundane_071','Sturdy Boots','Resoled leather travelling boots.',2,2),
('mundane_072','Wide-Brim Hat','A felt hat offering shade and rain cover.',0.5,0.5),
('mundane_073','Cloth Scarf','A long dyed wool scarf.',0.2,0),
('mundane_074','Silver Brooch','A modest decorative cloak pin.',5,0),
('mundane_075','Wooden Holy Symbol','A simple carved devotional token.',1,0),
('mundane_076','Deck of Playing Cards','A painted deck in a leather sleeve.',0.5,0),
('mundane_077','Bone Dice Set','Six carved bone dice in a pouch.',0.1,0),
('mundane_078','Dragonchess Set','A wooden three-tier strategy game.',1,0.5),
('mundane_079','Carved Flute','A plain wooden travelling flute.',2,1),
('mundane_080','Hand Drum','A hide-covered frame drum.',6,3),
('mundane_081','Lute Strings','A wrapped set of replacement gut strings.',1,0),
('mundane_082','Face Paint Kit','Grease paints in six earthy colours.',1,1),
('mundane_083','Disguise Wig','A convincing shoulder-length hairpiece.',2,1),
('mundane_084','Perfume Vial','A small vial of floral perfume.',5,0),
('mundane_085','Soap Bar','A block of strongly scented lye soap.',0.02,0.5),
('mundane_086','Comb','A small carved bone comb.',0.05,0),
('mundane_087','Razor','A folding steel shaving razor.',1,0),
('mundane_088','Bath Towel','A large absorbent linen cloth.',0.2,1),
('mundane_089','Bandage Roll','Clean linen strips without medicinal treatment.',0.2,0.5),
('mundane_090','Walking Cane','A polished hardwood walking stick.',0.5,3),
('mundane_091','Ten-Foot Pole','A straight ash pole useful for probing hazards.',0.1,7),
('mundane_092','Wooden Bucket','A coopered bucket with rope handle.',0.05,2),
('mundane_093','Iron Pot Hook','An adjustable hook for cooking over a fire.',0.1,1),
('mundane_094','Door Wedge','A hardwood wedge for holding a door.',0.02,0.5),
('mundane_095','Small Sandbag','A tied canvas bag filled with dry sand.',0.05,10),
('mundane_096','Canvas Tarpaulin','A waterproofed ten-foot square sheet.',2,12),
('mundane_097','Wooden Marbles','A pouch of twenty coloured wooden marbles.',0.1,1),
('mundane_098','Ball of Twine','Two hundred feet of light jute twine.',0.1,1),
('mundane_099','Empty Vials (5)','Five corked glass sample vials.',1,0.5),
('mundane_100','Small Wooden Box','A palm-sized hinged box with a brass catch.',0.5,1)
)
INSERT INTO items(id,name,item_type,description,value,weight,category,updated_at)
SELECT id,name,'item',description,value,weight,'mundane_loot',now() FROM mundane
ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,
  value=EXCLUDED.value,weight=EXCLUDED.weight,category=EXCLUDED.category,updated_at=now();

COMMIT;
