BEGIN;

ALTER TABLE weapons ADD COLUMN IF NOT EXISTS magical_properties JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE armour ADD COLUMN IF NOT EXISTS magical_properties JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE items ADD COLUMN IF NOT EXISTS magical_properties JSONB NOT NULL DEFAULT '{}'::jsonb;

WITH curios(name,description,effect_name) AS (
  SELECT * FROM unnest(
    ARRAY['Everhot Bucket','Self-Sweeping Broom','Whispering Teacup','Moonlit Mirror','Bottomless Inkpot','Rain-Fearing Umbrella','Unlosable Key','Singing Kettle','Truth-Tinged Spoon','Warmstone Pillow','Mending Needle','North-Seeking Button','Glowworm Lantern','Dryfoot Boots','Echo Bottle','Sleepless Alarm Bell','Colour-Changing Scarf','Polite Doorstop','Weatherwise Pinecone','Never-Dull Quill','Hearthspark Tinderbox','Cooling Wine Cup','Floating Washbasin','Dustless Rug','Counting Abacus','Memory Ribbon','Silent Dinner Bell','Shadow Candle','Honest Dice','Returning Cork','Dancing Marionette','Invisible Clothesline','Scented Handkerchief','Endless Chalk','Pocket Sundial','Dreamcatcher Net','Tidy Backpack','Featherweight Frying Pan','Map-Marking Compass','Borrowed-Voice Mask'],
    ARRAY['Always hot to the touch but never burns its bearer.','Sweeps a small room when commanded.','Repeats the last secret spoken over it.','Shows its surroundings as if under moonlight.','Produces ordinary black ink without emptying.','Closes itself before rain begins.','Tugs gently toward the lock it opens.','Sings softly when water reaches the boil.','Tastes bitter when used to eat a deliberate lie.','Remains pleasantly warm through the night.','Repairs a small tear after one minute of stitching.','Always rotates to point north.','Glows like a candle without flame or heat.','Keeps the wearer''s feet dry in ordinary water and mud.','Stores and repeats one minute of sound.','Rings at a chosen time and cannot be slept through.','Changes colour to complement the wearer''s clothes.','Politely complains when a door tries to close.','Predicts tomorrow''s weather by opening its scales.','Writes cleanly and never needs sharpening.','Lights dry tinder with a spoken command.','Chills any ordinary drink placed within it.','Hovers at waist height while filled with water.','Shakes itself clean each dawn.','Totals spoken numbers and clicks out the answer.','Retains a short written message until untied.','Makes no sound when struck unless its owner permits it.','Casts light but no visible flame.','Cannot be deliberately weighted or loaded.','Leaps back into its bottle when commanded.','Performs one dance it has been shown.','Supports clothing while remaining unseen.','Produces a chosen common scent for one hour.','Never grows shorter, though its marks remain ordinary.','Shows local noon even underground.','Softens mundane nightmares while hung over a bed.','Sorts its contents into labelled inner pockets.','Weighs almost nothing while being carried.','Marks the travelled route on a supplied map.','Repeats one sentence in the voice of its last wearer.'],
    ARRAY['warm','clean','record','moonlight','ink','weather','locate','boil','truth','comfort','mend','north','light','dry','record','alarm','colour','door','weather','write','ignite','cool','hover','clean','calculate','memory','silence','shadow_light','fairness','return','dance','support','scent','chalk','time','dream','organise','lightweight','map','voice']
  )
), numbered_curios AS (SELECT row_number() OVER() n,* FROM curios)
INSERT INTO items(id,name,item_type,description,value,weight,category,magical_properties,updated_at)
SELECT 'magic_item_'||lpad(n::text,3,'0'),name,'item',description,5+n,CASE WHEN n%5=0 THEN 2 ELSE .5 END,'magical_item',jsonb_build_object('is_magical',true,'effect',effect_name,'activation','utility'),now() FROM numbered_curios
ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,value=EXCLUDED.value,weight=EXCLUDED.weight,category='magical_item',magical_properties=EXCLUDED.magical_properties,updated_at=now();

WITH weapon_names(name) AS (SELECT unnest(ARRAY['Ember Longsword','Frostbite Dagger','Stormcall Spear','Sunflare Mace','Gravewhisper Axe','Venom Thorn Rapier','Thunderhead Hammer','Acid-Etched Scimitar','Moonbeam Shortbow','Starfire Longbow','Ashen Greatsword','Winterbite Handaxe','Lightning Rod Staff','Radiant Warhammer','Nightfall Shortsword','Poisoner''s Sickle','Rumbling Maul','Corrosive Trident','Dawn Dagger','Comet Javelin','Cinder Battleaxe','Rimeblade Rapier','Sparkfang Spear','Halo Flail','Wraithtouch Glaive','Adderbite Shortsword','Tempest Pike','Vitriol Sabre','Aurora Bow','Meteor Hammer'])), numbered AS (SELECT row_number() OVER() n,name FROM weapon_names), typed AS (SELECT *,(ARRAY['fire','cold','lightning','radiant','necrotic','poison','thunder','acid'])[((n-1)%8)+1] extra_type FROM numbered)
INSERT INTO weapons(id,name,description,value,weight,stat,damage_1,damage_type_1,damage_2,damage_type_2,proficient,magical_properties,updated_at)
SELECT 'magic_weapon_'||lpad(n::text,3,'0'),name,'An enchanted weapon dealing an additional 1d4 '||extra_type||' damage.',75+n*5,CASE WHEN n%5=0 THEN 6 ELSE 3 END,CASE WHEN n%3=0 THEN 'dex' ELSE 'str' END,CASE WHEN n%5=0 THEN '1d8' ELSE '1d6' END,CASE WHEN n%2=0 THEN 'piercing' ELSE 'slashing' END,'1d4',extra_type,true,jsonb_build_object('is_magical',true,'category','magical_item','effect','extra_damage','extra_damage_type',extra_type),now() FROM typed
ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,value=EXCLUDED.value,weight=EXCLUDED.weight,stat=EXCLUDED.stat,damage_1=EXCLUDED.damage_1,damage_type_1=EXCLUDED.damage_type_1,damage_2=EXCLUDED.damage_2,damage_type_2=EXCLUDED.damage_type_2,magical_properties=EXCLUDED.magical_properties,updated_at=now();

WITH armour_names(name) AS (SELECT unnest(ARRAY['Arrowturn Padded Armour','Emberguard Leather','Frostward Studded Leather','Stormhide Armour','Sunscale Shirt','Graveguard Breastplate','Venomward Half Plate','Thunderbrace Chain Mail','Acidguard Splint','Moonward Plate','Arrowturn Shield','Flamekeeper Chain Shirt','Winterguard Scale Mail','Sparkward Breastplate','Dawnwatch Half Plate','Duskguard Ring Mail','Serpentward Leather','Echo Ward Shield','Vitriol Guard Plate','Starward Studded Leather','Piercebane Chain Mail','Cinderhide Armour','Rimeguard Splint','Stormwall Shield','Radiant Scale Mail','Deathward Breastplate','Antivenom Plate','Thunderhide Leather','Acidward Chain Shirt','Celestial Half Plate'])), numbered AS (SELECT row_number() OVER() n,name FROM armour_names), typed AS (SELECT *,(ARRAY['piercing','fire','cold','lightning','radiant','necrotic','poison','thunder','acid'])[((n-1)%9)+1] resist FROM numbered)
INSERT INTO armour(id,name,description,value,weight,base_ac,armour_type,max_dex_bonus,proficient,magical_properties,updated_at)
SELECT 'magic_armour_'||lpad(n::text,3,'0'),name,'Enchanted armour granting resistance to '||resist||' damage while equipped.',100+n*8,CASE WHEN n%5=0 THEN 40 ELSE 15 END,CASE WHEN n%5=0 THEN 16 ELSE 12 END,CASE WHEN n%5=0 THEN 'Heavy' WHEN n%4=0 THEN 'Shield' ELSE 'Light' END,CASE WHEN n%5=0 THEN 0 ELSE 99 END,true,jsonb_build_object('is_magical',true,'category','magical_item','resistances',jsonb_build_array(resist)),now() FROM typed
ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,value=EXCLUDED.value,weight=EXCLUDED.weight,base_ac=EXCLUDED.base_ac,armour_type=EXCLUDED.armour_type,max_dex_bonus=EXCLUDED.max_dex_bonus,magical_properties=EXCLUDED.magical_properties,updated_at=now();

COMMIT;
