BEGIN;

CREATE TABLE IF NOT EXISTS animals (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  species TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  speed INTEGER NOT NULL CHECK (speed > 0),
  armour_class INTEGER NOT NULL CHECK (armour_class > 0),
  max_hp INTEGER NOT NULL CHECK (max_hp > 0),
  gold_value NUMERIC NOT NULL DEFAULT 0 CHECK (gold_value >= 0),
  mountable BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $migration$
DECLARE character_id_type TEXT;
BEGIN
  SELECT format_type(a.atttypid, a.atttypmod) INTO character_id_type
  FROM pg_attribute a WHERE a.attrelid='character_blobs'::regclass AND a.attname='id';
  EXECUTE format($sql$
    CREATE TABLE IF NOT EXISTS character_animals (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      character_id %s NOT NULL REFERENCES character_blobs(id) ON DELETE CASCADE,
      animal_id TEXT NOT NULL REFERENCES animals(id) ON UPDATE CASCADE,
      custom_name TEXT,
      current_hp INTEGER NOT NULL,
      notes TEXT NOT NULL DEFAULT '',
      acquired_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  $sql$, character_id_type);
END $migration$;

CREATE INDEX IF NOT EXISTS character_animals_character_idx ON character_animals(character_id);

WITH kinds(species,base_name,description,speed,ac,hp,value,mountable) AS (
  VALUES
    ('Horse','Horse','A dependable horse bred for travel, work, or war.',60,11,19,75,true),
    ('Pony','Pony','A sure-footed smaller mount suited to light riders and rough paths.',40,10,11,30,true),
    ('Donkey','Donkey','A patient pack animal with excellent footing and a stubborn streak.',40,10,11,18,true),
    ('Mule','Mule','A strong, reliable pack animal capable of carrying a light rider.',40,10,13,25,true),
    ('Camel','Camel','A long-legged desert mount able to endure heat and scarce water.',50,9,15,50,true),
    ('Elk','Elk','A tall woodland beast sometimes trained as an unusual riding animal.',50,10,13,65,true),
    ('Giant Goat','Giant Goat','A powerful horned beast able to negotiate steep and broken ground.',40,11,19,40,true),
    ('Ox','Ox','A heavy draught animal prized for strength rather than speed.',30,10,22,35,false),
    ('Hound','Hound','A trained dog suited to guarding, hunting, tracking, or companionship.',40,12,8,12,false),
    ('Boar','Boar','A tough, bristled animal kept for meat, breeding, or an eccentric companion.',40,11,11,20,false)
), strains(prefix,speed_mod,ac_mod,hp_mod,value_mod) AS (
  VALUES
    ('Ashen',0,0,0,0),('Dappled',0,0,1,5),('Fae-Bred',5,1,0,20),('Highland',-5,0,3,10),
    ('Marsh',-5,1,2,5),('Moon-Pale',0,0,0,10),('Red',5,0,-1,5),('Royal',0,1,2,25),
    ('Shaggy',-5,0,3,0),('White-Starred',5,0,0,10)
), catalogue AS (
  SELECT row_number() OVER (ORDER BY k.species,s.prefix) AS n,
    s.prefix||' '||k.base_name AS name,k.species,
    k.description||' This '||lower(s.prefix)||' strain has its own recognised temperament and breeding history.' AS description,
    greatest(20,k.speed+s.speed_mod) speed,greatest(5,k.ac+s.ac_mod) ac,greatest(1,k.hp+s.hp_mod) hp,
    greatest(1,k.value+s.value_mod) value,k.mountable
  FROM kinds k CROSS JOIN strains s
)
INSERT INTO animals(id,name,species,description,speed,armour_class,max_hp,gold_value,mountable,updated_at)
SELECT 'animal_'||lpad(n::text,3,'0'),name,species,description,speed,ac,hp,value,mountable,now() FROM catalogue
ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,species=EXCLUDED.species,description=EXCLUDED.description,
speed=EXCLUDED.speed,armour_class=EXCLUDED.armour_class,max_hp=EXCLUDED.max_hp,
gold_value=EXCLUDED.gold_value,mountable=EXCLUDED.mountable,updated_at=now();

COMMIT;
