BEGIN;

DO $migration$
DECLARE character_id_type TEXT;
BEGIN
  SELECT format_type(a.atttypid,a.atttypmod) INTO character_id_type
  FROM pg_attribute a WHERE a.attrelid='character_blobs'::regclass AND a.attname='id';
  EXECUTE format($sql$
    CREATE TABLE IF NOT EXISTS character_glyphs(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      character_id %s NOT NULL REFERENCES character_blobs(id) ON DELETE CASCADE,
      glyph_type TEXT NOT NULL CHECK(glyph_type IN ('rune','ward','enhancement')),
      rank TEXT NOT NULL CHECK(rank IN ('Minor','Major','Arcane','Cursed')),
      name TEXT NOT NULL,
      effect_description TEXT NOT NULL DEFAULT '',
      material TEXT,
      target_item_instance_id TEXT,
      size_ft NUMERIC,
      enhancement_days INTEGER,
      crafting_hours_required NUMERIC NOT NULL CHECK(crafting_hours_required>=0),
      crafting_hours_completed NUMERIC NOT NULL DEFAULT 0 CHECK(crafting_hours_completed>=0),
      resource_type TEXT NOT NULL CHECK(resource_type IN ('sindre','hp')),
      resource_cost INTEGER NOT NULL DEFAULT 0 CHECK(resource_cost>=0),
      arcane_score INTEGER NOT NULL,
      active_duration_rounds INTEGER,
      active_until_day INTEGER,
      active_until_round INTEGER,
      instability_damage TEXT,
      instability_radius_ft INTEGER,
      replenishment_dice TEXT,
      replenishment_multiplier INTEGER,
      status TEXT NOT NULL DEFAULT 'crafting' CHECK(status IN ('crafting','ready','active','depleted','broken','expended')),
      metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      completed_at TIMESTAMPTZ,
      activated_at TIMESTAMPTZ,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  $sql$,character_id_type);
END $migration$;

CREATE INDEX IF NOT EXISTS character_glyphs_owner_idx ON character_glyphs(character_id,status,created_at DESC);

WITH materials(id,name,value,description) AS (VALUES
('glyph_mat_001','Clay Rune Blank',1,'A shaped clay blank ready to receive a rune.'),
('glyph_mat_002','Wood Rune Blank',3,'A seasoned wooden blank ready for careful carving.'),
('glyph_mat_003','Stone Rune Blank',8,'A smooth stone blank prepared for a lasting rune.'),
('glyph_mat_004','Metal Rune Blank',20,'A metal blank suitable for welding an enduring rune.'),
('glyph_mat_005','Wooden Chisel',2,'A carving tool used for wooden rune blanks.'),
('glyph_mat_006','Stone Chisel',5,'A hard chisel used for stone rune blanks.'),
('glyph_mat_007','Welding Tools',25,'Portable tools for inscribing metal rune blanks.'),
('glyph_mat_008','Arcane Chalk',10,'Charged chalk used to trace a minor ward.'),
('glyph_mat_009','Iron Filings',3,'Fine iron filings used to anchor a minor ward.'),
('glyph_mat_010','Moonwater',8,'Water collected beneath an unobscured moon.'),
('glyph_mat_011','Raven Feather',2,'A clean feather from a raven, used to direct ward lines.'),
('glyph_mat_012','Sindre-Infused Obsidian',200,'Obsidian infused with a substantial reserve of Sindre.'),
('glyph_mat_013','Heartwood Dust',20,'Fine dust taken from the heartwood of an old tree.'),
('glyph_mat_014','Burned Ash',5,'Consecrated ash burned under controlled conditions.'),
('glyph_mat_015','Vial of Willing Sorcerer''s Blood',80,'Blood freely given by a sorcerer for major warding.'),
('glyph_mat_016','Enchanted Ink',35,'Stable ink capable of carrying a major ward pattern.'),
('glyph_mat_017','Etherglass Shard',250,'A translucent shard that catches light from elsewhere.'),
('glyph_mat_018','Meteorite Fragment',300,'A fragment of metal and stone fallen from the sky.'),
('glyph_mat_019','Elemental Scale',275,'A scale retaining the resonance of an elemental creature.'),
('glyph_mat_020','Banshee Tear',325,'A crystallised tear carrying a mournful arcane vibration.'),
('glyph_mat_021','Silver Thread',40,'Pure silver thread for binding complex ward geometry.'),
('glyph_mat_022','Rot-Root',15,'A corrupted root used in cursed ward construction.'),
('glyph_mat_023','Betrayer''s Bone Dust',100,'Powdered bone taken from a known betrayer.'),
('glyph_mat_024','Drowned Corpse Blood',75,'Preserved blood from a corpse recovered from water.'),
('glyph_mat_025','Cursed Charcoal',30,'Charcoal taken from a burned enchanted object.'),
('glyph_mat_026','Namebone',150,'A bone inscribed with the true name of its former owner.')
)
INSERT INTO items(id,name,item_type,description,value,weight,category,updated_at)
SELECT id,name,'item',description,value,.1,'crafting',now() FROM materials
ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,value=EXCLUDED.value,category='crafting',updated_at=now();

COMMIT;
