BEGIN;

-- Water is difficult terrain, not a solid obstacle. Repair maps generated by
-- older builds as well as establishing the current rule for future maps.
UPDATE map_tiles
SET move_cost = 2,
    blocks_movement = FALSE,
    blocks_vision = FALSE
WHERE lower(terrain) = 'water';

COMMIT;
