library(shiny)

controlMerchantsUI<-function(id){ns<-NS(id);tagList(
  div(class="control-card",div(class="control-section-title","Merchant Generator"),p(class="control-mini","Generate persistent merchant stock from the Control catalogue, inspect it, then invite players in the active session."),
    fluidRow(column(3,textInput(ns("name"),"Merchant name","Travelling Merchant")),column(3,selectInput(ns("wealth"),"Merchant class",c("Poor"="poor","Moderate"="moderate","Rich"="rich"))),column(3,selectInput(ns("specialty"),"Stock",c("General goods"="general","Livestock & mounts"="livestock","Provisions & travel"="provisions","Food seller"="food","Weapons dealer"="weapons","Armourer"="armour","Hunter & ranger"="hunter","Apothecary"="apothecary","Arcane curios"="arcane","Outfitter"="outfitter","Luxury goods"="luxury","Blacksmith"="smith","Materials & tools"="materials"))),column(3,selectInput(ns("temperament"),"Haggling",c("Fair"="fair","Hard haggler"="hard","Generous"="generous")))),
    fluidRow(column(4,selectInput(ns("pricing_style"),"Product pricing",c("Standard prices"="standard","Cheap"="cheap","Expensive"="expensive","Very expensive"="very_expensive"))),column(4,numericInput(ns("stock_count"),"Different wares in stock",8,min=1,max=100,step=1)),column(4,p(class="control-mini",style="padding-top:25px","Equipment material and build quality alter its base value before merchant pricing and haggling."))),
    actionButton(ns("generate"),"Generate Stock",class="btn btn-primary"),actionButton(ns("save"),"Save Merchant",class="btn btn-success"),br(),br(),uiOutput(ns("summary")),DT::DTOutput(ns("preview"))),
  div(class="control-card",div(class="control-section-title","Open Merchant for Players"),selectInput(ns("merchant_id"),"Saved merchant",choices=character()),uiOutput(ns("saved_summary")),DT::DTOutput(ns("saved_stock")),div(class="merchant-invite-panel",checkboxGroupInput(ns("players"),"Choose players to invite",choices=character()),div(class="merchant-invite-actions",actionButton(ns("invite"),"Send Merchant Invitation",class="btn btn-success"),actionButton(ns("close"),"Close Merchant",class="btn btn-default")))),
  div(class="control-card",div(class="control-section-title","Chest Generator"),p(class="control-mini","Create a shared treasure chest, choose its theme and lock, then present it to selected players."),fluidRow(column(3,textInput(ns("chest_name"),"Chest name","Weathered Strongbox")),column(3,selectInput(ns("chest_theme"),"Contents",c("Mixed treasure"="general","Traveller's cache"="traveller","War chest"="war","Hunter's cache"="hunter","Provisions"="provisions","Arcane cache"="arcane","Noble valuables"="noble","Crafting materials"="materials"))),column(3,selectInput(ns("chest_difficulty"),"Lock",c("Unlocked"="unlocked","Easy"="easy","Standard"="standard","Hard"="hard","Master"="master"))),column(3,numericInput(ns("chest_items"),"Different items",4,min=1,max=30,step=1))),actionButton(ns("generate_chest"),"Generate Contents",class="btn btn-primary"),actionButton(ns("save_chest"),"Save Chest",class="btn btn-success"),br(),br(),uiOutput(ns("chest_draft_summary")),DT::DTOutput(ns("chest_preview"))),
  div(class="control-card",div(class="control-section-title","Present Chest to Players"),selectInput(ns("chest_id"),"Saved chest",choices=character()),uiOutput(ns("chest_summary")),DT::DTOutput(ns("chest_stock")),checkboxGroupInput(ns("chest_players"),"Choose players",choices=character()),div(class="merchant-invite-actions",actionButton(ns("invite_chest"),"Reveal Chest",class="btn btn-success"),actionButton(ns("unlock_chest"),"DM Unlock",class="btn btn-warning"),actionButton(ns("close_chest"),"Remove Chest",class="btn btn-default")))
)}

controlMerchantsServer<-function(id,ctrl,players_tbl,bump_refresh=NULL){moduleServer(id,function(input,output,session){`%||%`<-get("%||%",inherits=TRUE);draft<-reactiveVal(NULL);saved_rev<-reactiveVal(0L);chest_draft<-reactiveVal(NULL);chest_rev<-reactiveVal(0L);pending_remove_chest<-reactiveVal(NA_integer_);pending_close_merchant<-reactiveVal(NA_integer_)
  catalogue<-function(){base<-lapply(names(enemy_loot_catalog()),function(id){x<-enemy_loot_catalog()[[id]];x$id<-id;x});db<-get_control_catalogue_definitions();path<-file.path("control_app","data","control_inventory.rds");local<-if(file.exists(path))tryCatch(readRDS(path),error=function(e)list())else list();all<-c(local,db,base);seen<-character();Filter(function(x){id<-as.character(x$id%||%"");keep<-nzchar(id)&&!id%in%seen;seen<<-c(seen,id);keep},all)}
  eligible<-function(items,specialty){Filter(function(x){typ<-tolower(as.character(x$type%||%"item"));category<-tolower(as.character((x$meta%||%list())$category%||%""));pools<-tolower(as.character(x$pools%||%character()));nm<-tolower(as.character(x$name%||%""));switch(specialty,general=typ!="animal",livestock=typ=="animal",provisions=category%in%c("food","mundane_loot","tool"),food=category=="food",weapons=typ=="weapon",armour=typ%in%c("armor","armour"),hunter=typ!="animal"&&(any(pools%in%c("hunter","ranger","animal"))||grepl("bow|arrow|trap|pelt|knife|jerky|ration",nm)),apothecary=category%in%c("consumable","magical_item")||grepl("draught|potion|herb|remedy|poison",nm),arcane=category%in%c("magical_item","crafting")||grepl("glyph|scroll|crystal|dust",nm),outfitter=category%in%c("mundane_loot","tool")||typ%in%c("armor","armour"),luxury=category%in%c("treasure","magical_item")||as.numeric(x$value%||%0)>=25,smith=typ%in%c("weapon","armor","armour"),materials=category%in%c("crafting","tool"),FALSE)},items)}
  generate<-function(){wealth<-input$wealth%||%"moderate";specialty<-input$specialty%||%"general";pool<-eligible(catalogue(),specialty);if(!length(pool))pool<-catalogue();n<-max(1L,as.integer(input$stock_count%||%8L));chosen<-merchant_select_stock(pool,min(n,length(pool)),specialty);chosen<-lapply(chosen,function(item){item$catalogue_id<-item$id;item$qty<-if((item$type%||%"")%in%c("consumable","item"))sample(1:5,1)else 1L;rolled<-roll_loot_equipment_provenance(list(item),enemy_type=if(wealth=="rich")"Boss"else"Merchant",characteristics=character())[[1L]];rolled$value<-equipment_adjusted_value(rolled);rolled});list(name=trimws(input$name%||%"Merchant"),wealth=wealth,specialty=specialty,temperament=input$temperament%||%"fair",pricing_style=input$pricing_style%||%"standard",gold=c(poor=15,moderate=75,rich=250)[[wealth]],stock=chosen)}
  item_details<-function(x){m<-x$meta%||%list();type<-tolower(as.character(x$type%||%"item"));parts<-character();if(type=="weapon")parts<-c(parts,paste0("Damage ",m$damage1%||%"1d4"," ",m$dmg_type1%||%"other",if(nzchar(as.character(m$damage2%||%"")))paste0(" + ",m$damage2," ",m$dmg_type2%||%"other")else""," · ",toupper(m$stat%||%"str")));if(type%in%c("armor","armour"))parts<-c(parts,paste0(m$type%||%"Armour"," · AC ",m$base_ac%||%"—",if((m$equipment_slot%||%"body")!="body")paste0(" · +",m$ac_bonus%||%0," AC ",m$equipment_slot)else""));if(type=="animal")parts<-c(parts,paste0(m$species%||%"Animal"," · Speed ",m$speed%||%30," · AC ",m$armour_class%||%10," · HP ",m$max_hp%||%5," · ",if(isTRUE(m$mountable))"Mountable"else"Unmountable"));if((m$category%||%"")=="food")parts<-c(parts,paste0(m$ration_value%||%1," ration(s) · ",m$shelf_life_days%||%3," fresh days"));if(nzchar(as.character(m$effect%||%"")))parts<-c(parts,paste0("Effect: ",gsub("_"," ",m$effect)," ",m$effect_amount%||%""));paste(parts,collapse=" | ")}
  draft_frame<-function(stock){if(!length(stock))return(data.frame());do.call(rbind,lapply(stock,function(x){m<-x$meta%||%list();data.frame(Item=x$name%||%"Item",Type=x$type%||%"item",Description=x$desc%||%"",Details=item_details(x),Quantity=x$qty%||%1,BaseValue=x$value%||%0,Material=m$material%||%"—",Quality=m$build_quality%||%"—",stringsAsFactors=FALSE)}))}
  saved_frame<-function(s){if(!nrow(s))return(data.frame());do.call(rbind,lapply(seq_len(nrow(s)),function(i){item<-enemy_db_json(s$item_json[[i]],list());m<-item$meta%||%list();data.frame(Item=item$name%||%"Item",Type=item$type%||%"item",Description=item$desc%||%"",Details=item_details(item),Quantity=s$quantity[[i]],BaseValue=s$base_value[[i]],Material=m$material%||%"—",Quality=m$build_quality%||%"—",stringsAsFactors=FALSE)}))}
  observeEvent(input$generate,{draft(generate())},ignoreInit=TRUE)
  output$summary<-renderUI({d<-draft();if(is.null(d))return(p("Generate stock to preview it."));p(strong(d$name)," · ",tools::toTitleCase(d$wealth)," · ",tools::toTitleCase(d$specialty)," · ",tools::toTitleCase(gsub("_"," ",d$pricing_style))," pricing · ",d$gold," gold · ",length(d$stock)," stock lines")})
  output$preview<-DT::renderDT({d<-draft();if(is.null(d)||!length(d$stock))return(NULL);DT::datatable(draft_frame(d$stock),rownames=FALSE,escape=TRUE,options=list(dom="t",scrollX=TRUE,pageLength=-1,columnDefs=list(list(width="280px",targets=2),list(width="260px",targets=3))))})
  refresh_merchants<-function(){saved_rev(isolate(saved_rev())+1L)}
  observe({saved_rev();sid<-suppressWarnings(as.integer(ctrl$session_id%||%NA));m<-if(!is.na(sid))list_session_merchants(sid,TRUE)else data.frame();choices<-if(nrow(m))setNames(as.character(m$id),paste0(m$name," · ",m$gold,"g"))else character();updateSelectInput(session,"merchant_id",choices=choices)})
  selected_bundle<-reactive({saved_rev();mid<-suppressWarnings(as.integer(input$merchant_id%||%NA));if(is.na(mid))NULL else get_merchant_bundle(mid)})
  output$saved_summary<-renderUI({b<-selected_bundle();if(is.null(b))return(NULL);m<-b$merchant;p(strong(m$name[[1L]])," · ",tools::toTitleCase(m$wealth_class[[1L]])," · ",tools::toTitleCase(m$temperament[[1L]])," · ",tools::toTitleCase(gsub("_"," ",m$pricing_style[[1L]]%||%"standard"))," pricing · purse ",m$gold[[1L]],"g")})
  output$saved_stock<-DT::renderDT({b<-selected_bundle();if(is.null(b)||!nrow(b$stock))return(NULL);DT::datatable(saved_frame(b$stock),rownames=FALSE,escape=TRUE,options=list(dom="t",scrollX=TRUE,pageLength=-1,columnDefs=list(list(width="280px",targets=2),list(width="260px",targets=3))))})
  observe({p<-players_tbl();if(!is.data.frame(p)||!nrow(p))return(updateCheckboxGroupInput(session,"players",choices=character()));ids<-as.character(p$character_id);labels<-as.character(p$display_name%||%p$char_name%||%ids);updateCheckboxGroupInput(session,"players",choices=setNames(ids,labels),selected=intersect(isolate(input$players%||%character()),ids))})
  observe({p<-players_tbl();ids<-if(is.data.frame(p)&&nrow(p))as.character(p$character_id)else character();labels<-if(length(ids))as.character(p$display_name%||%p$char_name%||%ids)else character();updateCheckboxGroupInput(session,"chest_players",choices=setNames(ids,labels),selected=intersect(isolate(input$chest_players%||%character()),ids))})
  observeEvent(input$save,{d<-draft();sid<-suppressWarnings(as.integer(ctrl$session_id%||%NA));if(is.null(d)||is.na(sid))return(showNotification("Generate stock and select a session first.",type="error"));m<-create_merchant(sid,d$name,d$wealth,d$specialty,d$temperament,d$gold,d$stock,d$pricing_style);if(is.null(m))return(showNotification("Merchant could not be saved.",type="error"));refresh_merchants();updateSelectInput(session,"merchant_id",selected=as.character(m$id[[1L]]));showNotification("Merchant saved and ready to invite.",type="message")},ignoreInit=TRUE)
  observeEvent(input$invite,{mid<-suppressWarnings(as.integer(input$merchant_id));ids<-as.character(input$players%||%character());if(is.na(mid)||!length(ids))return(showNotification("Choose a merchant and at least one player.",type="warning"));if(!invite_players_to_merchant(mid,ids))return(showNotification("Invitations could not be sent.",type="error"));showNotification("Merchant invitations sent.",type="message")},ignoreInit=TRUE)
  observeEvent(input$close,{mid<-suppressWarnings(as.integer(input$merchant_id));if(is.na(mid))return();pending_close_merchant(mid);showModal(modalDialog(title="Close this merchant?",p("Players will immediately lose access to this merchant and any open shop window."),footer=tagList(modalButton("Keep Merchant"),actionButton(session$ns("confirm_close_merchant"),"Close Merchant",class="btn btn-danger")),easyClose=FALSE))},ignoreInit=TRUE)
  observeEvent(input$confirm_close_merchant,{mid<-pending_close_merchant();removeModal();if(is.na(mid))return();con<-get_db_connection();if(is.null(con))return();on.exit(release_db_connection(con),add=TRUE);DBI::dbExecute(con,"UPDATE merchants SET status='closed',updated_at=now() WHERE id=$1",params=list(mid));pending_close_merchant(NA_integer_);refresh_merchants();showNotification("Merchant closed.")},ignoreInit=TRUE)
  observeEvent(input$generate_chest,{theme<-input$chest_theme%||%"general";pool<-Filter(function(x){typ<-tolower(as.character(x$type%||%"item"));meta<-x$meta%||%list();cat<-tolower(as.character(meta$category%||%""));nm<-tolower(as.character(x$name%||%""));if(typ=="animal")return(FALSE);switch(theme,general=TRUE,traveller=cat%in%c("tool","food","mundane_loot")||grepl("ration|rope|torch|lockpick|draught",nm),war=typ%in%c("weapon","armor","armour")||grepl("shield|draught",nm),hunter=grepl("bow|arrow|trap|pelt|spear|dagger|ration",nm),provisions=cat=="food"||grepl("ration|water|draught",nm),arcane=cat%in%c("magical_item","crafting")||grepl("glyph|rune|crystal|dust|draught",nm),noble=cat%in%c("treasure","magical_item")||as.numeric(x$value%||%0)>=25,materials=cat%in%c("crafting","tool")||grepl("fragment|dust|pelt|tools",nm),TRUE)},catalogue());if(!length(pool))pool<-Filter(function(x)tolower(as.character(x$type%||%"item"))!="animal",catalogue());n<-min(length(pool),max(1L,as.integer(input$chest_items%||%4L)));chosen<-if(n)sample(pool,n)else list();chosen<-lapply(chosen,function(item){item$catalogue_id<-item$id;item$qty<-if((item$type%||%"")%in%c("consumable","item"))sample(1:3,1)else 1L;roll_loot_equipment_provenance(list(item),enemy_type="Treasure",characteristics=character())[[1L]]});chest_draft(list(name=trimws(input$chest_name%||%"Chest"),difficulty=input$chest_difficulty%||%"standard",theme=theme,items=chosen))},ignoreInit=TRUE)
  output$chest_draft_summary<-renderUI({d<-chest_draft();if(is.null(d))return(p("Generate contents to preview them."));p(strong(d$name)," · ",tools::toTitleCase(gsub("_"," ",d$theme%||%"general"))," · ",tools::toTitleCase(d$difficulty)," · ",length(d$items)," item lines")})
  output$chest_preview<-DT::renderDT({d<-chest_draft();if(is.null(d)||!length(d$items))return(NULL);DT::datatable(draft_frame(d$items),rownames=FALSE,options=list(dom="t",scrollX=TRUE))})
  observeEvent(input$save_chest,{d<-chest_draft();sid<-suppressWarnings(as.integer(ctrl$session_id%||%NA));if(is.null(d)||is.na(sid))return(showNotification("Generate a chest and select a session first.",type="error"));ch<-create_chest(sid,d$name,if(d$difficulty=="unlocked")"standard"else d$difficulty,d$items,d$difficulty!="unlocked");if(is.null(ch))return(showNotification("Chest could not be saved. Run database migrations first.",type="error"));chest_rev(chest_rev()+1L);updateSelectInput(session,"chest_id",selected=as.character(ch$id[[1L]]));showNotification("Chest saved.")},ignoreInit=TRUE)
  observe({chest_rev();sid<-suppressWarnings(as.integer(ctrl$session_id%||%NA));rows<-if(is.na(sid))data.frame()else list_session_chests(sid,TRUE);choices<-if(nrow(rows))setNames(as.character(rows$id),paste0(rows$name," · ",ifelse(rows$locked,tools::toTitleCase(rows$difficulty),"Unlocked")))else character();updateSelectInput(session,"chest_id",choices=choices)})
  chest_bundle<-reactive({chest_rev();id<-suppressWarnings(as.integer(input$chest_id%||%NA));if(is.na(id))NULL else get_chest_bundle(id)})
  output$chest_summary<-renderUI({b<-chest_bundle();if(is.null(b))return(NULL);ch<-b$chest;p(strong(ch$name[[1L]])," · ",if(isTRUE(ch$locked[[1L]]))paste(tools::toTitleCase(ch$difficulty[[1L]]),"lock")else"Unlocked"," · ",sum(b$items$quantity%||%0)," items remain")})
  output$chest_stock<-DT::renderDT({b<-chest_bundle();if(is.null(b)||!nrow(b$items))return(NULL);DT::datatable(saved_frame(transform(b$items,base_value=0)),rownames=FALSE,options=list(dom="t",scrollX=TRUE))})
  observeEvent(input$invite_chest,{id<-as.integer(input$chest_id%||%NA);ids<-as.character(input$chest_players%||%character());if(is.na(id)||!length(ids))return(showNotification("Choose a chest and at least one player.",type="warning"));if(!invite_players_to_chest(id,ids))return(showNotification("Chest could not be revealed.",type="error"));showNotification("Chest revealed to the selected players.")},ignoreInit=TRUE)
  update_chest<-function(sql,message){id<-as.integer(input$chest_id%||%NA);if(is.na(id))return();con<-get_db_connection();if(is.null(con))return();on.exit(release_db_connection(con),add=TRUE);DBI::dbExecute(con,sql,params=list(id));chest_rev(chest_rev()+1L);showNotification(message)}
  observeEvent(input$unlock_chest,update_chest("UPDATE chests SET locked=FALSE,updated_at=now() WHERE id=$1","Chest unlocked."),ignoreInit=TRUE)
  observeEvent(input$close_chest,{id<-as.integer(input$chest_id%||%NA);if(is.na(id))return();pending_remove_chest(id);showModal(modalDialog(title="Remove this chest?",p("Players will immediately lose access. Any items left inside will no longer be available."),footer=tagList(modalButton("Keep Chest"),actionButton(session$ns("confirm_remove_chest"),"Remove Chest",class="btn btn-danger")),easyClose=FALSE))},ignoreInit=TRUE)
  observeEvent(input$confirm_remove_chest,{id<-pending_remove_chest();removeModal();if(is.na(id))return();con<-get_db_connection();if(is.null(con))return();on.exit(release_db_connection(con),add=TRUE);DBI::dbExecute(con,"UPDATE chests SET status='closed',updated_at=now() WHERE id=$1",params=list(id));pending_remove_chest(NA_integer_);chest_rev(chest_rev()+1L);showNotification("Chest removed.")},ignoreInit=TRUE)
})}
