library(shiny)
library(DT)

merge_npc_feature_catalogue<-function(saved=list()){
  defaults<-lapply(unname(npc_feature_catalogue()),function(x){x$rules<-lapply(x$loot_ids%||%character(),function(id)list(item_id=id,chance=100,group="",required=FALSE));x})
  retired_ids<-c("Barbarian","Speedy","Boss","Fae","Animal","Armoured","Brute","Archer","Venomous","Undead","Fire_Touched","Regenerator","Spellcaster","feature_1786875037","feature_1787332754","feature_1787332755")
  retired_names<-tolower(c("Barbarian iron spear","Speedy","Boss","Fae","Animal","Armoured","Brute","Archer","Venomous","Undead","Fire-touched","Regenerator","Spellcaster","Iron blooded","Barbarian New Feature","New Feature"))
  saved<-Filter(function(x)!as.character(x$id%||%"")%in%retired_ids&&!tolower(trimws(as.character(x$name%||%"")))%in%retired_names,saved)
  default_ids<-vapply(defaults,`[[`,"","id");by_id<-setNames(saved,vapply(saved,function(x)as.character(x$id%||%""),character(1)))
  defaults<-lapply(defaults,function(x){old<-by_id[[x$id]];if(!is.null(old)&&identical(as.integer(old$feature_version%||%0L),as.integer(x$feature_version)))old else x})
  c(defaults,Filter(function(x)!as.character(x$id%||%"")%in%default_ids,saved))
}

controlNpcFeaturesUI <- function(id) {
  ns <- NS(id)
  tagList(div(class="control-card",
    div(class="control-section-title","NPC Feature / Characteristic Rules"),
    fluidRow(
      column(4, selectInput(ns("feature_id"),"Feature",choices=character()), textInput(ns("name"),"Name"),
             textInput(ns("desc"),"Description"), textInput(ns("ability_bonus"),"Ability changes",placeholder="str=2, dex=-1"),
             selectInput(ns("category"),"Layer",c("Occupation"="occupation","Training"="training","Allegiance"="allegiance","Rank"="rank","Physical"="physical","Equipment"="equipment","Magical discipline"="magical_discipline","Supernatural state"="supernatural_state","Anatomy"="anatomy","Behaviour"="behaviour","Encounter modifier"="encounter_modifier","Temporary state"="temporary_state","Design"="design")),
             textInput(ns("compatible_pools"),"Compatible pool IDs",placeholder="town_guard, house_soldier"),textInput(ns("requires_features"),"Required features"),textInput(ns("requires_equipment"),"Required equipment"),textInput(ns("exclusive_group"),"Exclusive group"),
             fluidRow(column(6,selectInput(ns("lore_status"),"Lore status",c("Canonical"="canonical","Mechanically inferred"="mechanically_inferred","Provisional"="provisional"))),column(6,selectInput(ns("rarity"),"Rarity",c("Core"="core","Uncommon"="uncommon","Rare"="rare","Elite"="elite","Boss"="boss")))),
             checkboxInput(ns("enabled_for_generation"),"Enabled for automatic generation",TRUE),
             numericInput(ns("hp_multiplier"),"HP multiplier",1,min=.1,step=.1), numericInput(ns("ac_bonus"),"AC bonus",0),
             numericInput(ns("movement_bonus"),"Movement bonus",0), selectizeInput(ns("attacks"),"Added natural / special attacks",choices=character(),multiple=TRUE),
             selectizeInput(ns("resistances"),"Resistances",choices=enemy_damage_types(),multiple=TRUE),selectizeInput(ns("immunities"),"Immunities",choices=enemy_damage_types(),multiple=TRUE),selectizeInput(ns("vulnerabilities"),"Vulnerabilities",choices=enemy_damage_types(),multiple=TRUE),selectizeInput(ns("condition_immunities"),"Condition immunities",choices=enemy_conditions(),multiple=TRUE),
             actionButton(ns("new_feature"),"New Feature"), actionButton(ns("save_feature"),"Save Feature",class="btn btn-primary")),
      column(8, h4("Inventory contributed by this feature"),
             fluidRow(column(4,selectInput(ns("item_id"),"Item",choices=character())),
                      column(2,numericInput(ns("chance"),"Chance / weight",100,min=0,max=100)),
                      column(3,textInput(ns("group"),"Alternative group")),
                      column(3,checkboxInput(ns("required"),"Guarantee group",FALSE))),
             fluidRow(column(6,selectInput(ns("rule_material"),"Default material roll",choices=c("Random"="","Copper","Iron","Steel","Titanium Copper","Wood"))),
                      column(6,selectInput(ns("rule_quality"),"Default build quality / condition",choices=c("Random"="","Very-Poorly-Crafted","Poorly-Crafted","Passably-Crafted","Bog-Standard","Well-Crafted","Master-Crafted")))),
             actionButton(ns("add_rule"),"Add / Update Rule"), actionButton(ns("remove_rule"),"Remove Rule"),
             h4("Current rules"),DTOutput(ns("rules_table")), actionButton(ns("roll_preview"),"Roll Example"), uiOutput(ns("preview")))
    )
  ))
}

controlNpcFeaturesServer<-function(id){moduleServer(id,function(input,output,session){`%||%`<-get("%||%",inherits=TRUE);path<-file.path("control_app","data","npc_features.rds");inv_path<-file.path("control_app","data","control_inventory.rds");dir.create(dirname(path),recursive=TRUE,showWarnings=FALSE)
  parse_bonus<-function(x){parts<-trimws(strsplit(x%||%"",",",fixed=TRUE)[[1]]);out<-numeric();for(p in parts){z<-trimws(strsplit(p,"=",fixed=TRUE)[[1]]);if(length(z)==2&&!is.na(as.numeric(z[2])))out[tolower(z[1])]<-as.numeric(z[2])};out}
  features<-reactiveVal({saved<-if(file.exists(path))tryCatch(readRDS(path),error=function(e)list())else list();merged<-merge_npc_feature_catalogue(saved);if(!identical(saved,merged))saveRDS(merged,path);merged});inventory_cache<-reactiveVal(list());inventory_file_sig<-reactiveVal("");observe({invalidateLater(1500,session);x<-if(file.exists(inv_path))tryCatch(readRDS(inv_path),error=function(e)list())else list();b<-lapply(names(enemy_loot_catalog()),function(k){z<-enemy_loot_catalog()[[k]];z$id<-k;z});ids<-vapply(x,function(z)z$id,character(1));out<-c(x,Filter(function(z)!z$id%in%ids,b));sig<-paste(vapply(out,function(z)paste(z$id,z$name,z$type,sep="~"),character(1)),collapse="|");if(!identical(sig,inventory_file_sig())){inventory_file_sig(sig);inventory_cache(out)}});inventory<-reactive(inventory_cache());active<-reactive({x<-Filter(function(z)identical(z$id,input$feature_id%||%""),features());if(length(x))x[[1]]else NULL});inventory_sig<-reactiveVal("");feature_choice_sig<-reactiveVal("");attack_choice_sig<-reactiveVal("")
  observe({x<-features();vals<-vapply(x,`[[`,"","id");labels<-vapply(x,`[[`,"","name");sig<-paste(vals,labels,collapse="|");if(!identical(sig,feature_choice_sig())){feature_choice_sig(sig);keep<-isolate(input$feature_id%||%"");updateSelectInput(session,"feature_id",choices=setNames(vals,labels),selected=if(keep%in%vals)keep else vals[1])};a<-Filter(function(z)!nzchar(as.character(z$loot_id%||%"")),enemy_attack_catalog());asig<-paste(names(a),vapply(a,`[[`,"","name"),collapse="|");if(!identical(asig,attack_choice_sig())){attack_choice_sig(asig);updateSelectizeInput(session,"attacks",choices=setNames(names(a),vapply(a,`[[`,"","name")),selected=intersect(isolate(input$attacks%||%character()),names(a)),server=TRUE)}})
  observe({x<-inventory();vals<-vapply(x,`[[`,"","id");sig<-paste(vals,vapply(x,`[[`,"","name"),collapse="|");if(identical(sig,inventory_sig()))return();inventory_sig(sig);keep<-isolate(input$item_id%||%"");updateSelectInput(session,"item_id",choices=setNames(vals,vapply(x,`[[`,"","name")),selected=if(keep%in%vals)keep else vals[1])})
  observeEvent(input$feature_id,{x<-active();if(is.null(x))return();updateTextInput(session,"name",value=x$name);updateTextInput(session,"desc",value=x$desc);updateTextInput(session,"ability_bonus",value=paste(names(x$ability_bonus),x$ability_bonus,sep="=",collapse=", "));for(field in c("category","lore_status","rarity"))updateSelectInput(session,field,selected=x[[field]]%||%switch(field,category="training",lore_status="mechanically_inferred",rarity="core"));for(field in c("compatible_pools","requires_features","requires_equipment"))updateTextInput(session,field,value=paste(x[[field]]%||%character(),collapse=", "));updateTextInput(session,"exclusive_group",value=x$exclusive_group%||%"");updateCheckboxInput(session,"enabled_for_generation",value=isTRUE(x$enabled_for_generation%||%TRUE));updateNumericInput(session,"hp_multiplier",value=x$hp_multiplier);updateNumericInput(session,"ac_bonus",value=x$ac_bonus);updateNumericInput(session,"movement_bonus",value=x$movement_bonus);updateSelectizeInput(session,"attacks",selected=x$attacks);for(f in c("resistances","immunities","vulnerabilities","condition_immunities"))updateSelectizeInput(session,f,selected=x[[f]]%||%character())},ignoreInit=TRUE)
  rule_rows<-reactive({x<-active();if(is.null(x)||!length(x$rules))return(data.frame());it<-inventory();do.call(rbind,lapply(x$rules,function(r){z<-Filter(function(i)identical(i$id,r$item_id),it);data.frame(item_id=r$item_id,item=if(length(z))z[[1]]$name else r$item_id,chance=paste0(r$chance,"%"),alternative_group=if(nzchar(r$group%||%""))r$group else "—",guaranteed=if(isTRUE(r$required))"Yes" else "No",material=if(nzchar(r$material%||%""))r$material else "Random",build_quality=if(nzchar(r$build_quality%||%""))r$build_quality else "Random",stringsAsFactors=FALSE)}))})
  output$rules_table<-renderDT({rows<-rule_rows();if(!nrow(rows))return(NULL);datatable(rows[,setdiff(names(rows),"item_id"),drop=FALSE],selection="single",rownames=FALSE,options=list(dom="t",paging=FALSE,ordering=FALSE))})
  save_all<-function(x){features(x);saveRDS(x,path)};observeEvent(input$new_feature,{x<-features();id<-paste0("feature_",as.integer(Sys.time()));x<-c(x,list(list(id=id,name="New Feature",desc="",ability_bonus=numeric(),hp_multiplier=1,ac_bonus=0,movement_bonus=0,attacks=character(),rules=list())));save_all(x);updateSelectInput(session,"feature_id",selected=id)})
  observeEvent(input$save_feature,{x<-features();i<-which(vapply(x,function(z)identical(z$id,input$feature_id),logical(1)))[1];if(is.na(i))return();x[[i]]$name<-input$name%||%x[[i]]$name;x[[i]]$desc<-input$desc%||%"";x[[i]]$ability_bonus<-parse_bonus(input$ability_bonus);x[[i]]$category<-input$category%||%"training";x[[i]]$lore_status<-input$lore_status%||%"mechanically_inferred";x[[i]]$rarity<-input$rarity%||%"core";parse_values<-function(v)unique(trimws(Filter(nzchar,strsplit(v%||%"",",",fixed=TRUE)[[1]])));for(field in c("compatible_pools","requires_features","requires_equipment"))x[[i]][[field]]<-parse_values(input[[field]]);x[[i]]$exclusive_group<-trimws(input$exclusive_group%||%"");x[[i]]$enabled_for_generation<-isTRUE(input$enabled_for_generation);x[[i]]$hp_multiplier<-input$hp_multiplier%||%1;x[[i]]$ac_bonus<-input$ac_bonus%||%0;x[[i]]$movement_bonus<-input$movement_bonus%||%0;x[[i]]$attacks<-input$attacks%||%character();for(f in c("resistances","immunities","vulnerabilities","condition_immunities"))x[[i]][[f]]<-input[[f]]%||%character();save_all(x);showNotification("Feature saved.")})
  alter<-function(remove=FALSE){x<-features();i<-which(vapply(x,function(z)identical(z$id,input$feature_id),logical(1)))[1];if(is.na(i))return();if(remove){row<-input$rules_table_rows_selected;rows<-rule_rows();if(!length(row)||!nrow(rows))return(showNotification("Select a rule in the table first.",type="warning"));id<-rows$item_id[[row[[1L]]]]}else id<-input$item_id;x[[i]]$rules<-Filter(function(r)!identical(r$item_id,id),x[[i]]$rules);if(!remove)x[[i]]$rules<-c(x[[i]]$rules,list(list(item_id=id,chance=input$chance%||%100,group=trimws(input$group%||%""),required=isTRUE(input$required),material=input$rule_material%||%"",build_quality=input$rule_quality%||%"")));save_all(x)};observeEvent(input$add_rule,alter(FALSE));observeEvent(input$remove_rule,alter(TRUE))
  rolled<-eventReactive(input$roll_preview,{x<-active();if(is.null(x))return(list());r<-x$rules;chosen<-Filter(function(z)!nzchar(z$group%||%"")&&runif(1)*100<=z$chance,r);g<-Filter(function(z)nzchar(z$group%||%""),r);for(set in split(g,vapply(g,function(z)z$group%||%"",character(1)))){if(any(vapply(set,function(z)isTRUE(z$required),logical(1)))||runif(1)*100<=sum(vapply(set,`[[`,0,"chance")))chosen<-c(chosen,list(sample(set,1,prob=vapply(set,`[[`,0,"chance"))[[1]]))};it<-inventory();items<-lapply(chosen,function(rule){z<-Filter(function(a)identical(a$id,rule$item_id),it);if(!length(z))return(NULL);item<-z[[1]];meta<-item$meta%||%list();if(nzchar(rule$material%||%"")||nzchar(rule$build_quality%||%"")){meta$lock_provenance<-TRUE;meta$material<-rule$material%||%"";meta$build_quality<-rule$build_quality%||%"";meta$provenance_assigned<-FALSE};item$meta<-meta;item});roll_loot_equipment_provenance(Filter(Negate(is.null),items),"Custom",input$feature_id%||%character())});output$preview<-renderUI({items<-rolled();if(!length(items))return(div(class="alert alert-info","This roll produced no inventory."));tagList(h5("Example result"),tags$ul(lapply(items,function(item){m<-item$meta%||%list();tags$li(paste(item$name,"—",m$material%||%"—","/",m$build_quality%||%"—"))})))})
})}
