library(shiny)

controlNpcAttacksUI<-function(id){ns<-NS(id);div(class="control-card",div(class="control-section-title","NPC Natural / Special Attack Designer"),p(class="control-mini","Weapons come from Control Inventory and automatically become attacks. Use this editor for anatomy-valid natural attacks, tactics and deliberately authored magic."),fluidRow(
  column(4,selectInput(ns("attack_id"),"Attack",choices=character()),textInput(ns("name"),"Name"),actionButton(ns("new_attack"),"New Attack")),
  column(8,fluidRow(column(3,numericInput(ns("hit"),"Hit bonus",2)),column(3,textInput(ns("damage"),"Damage","1d6")),column(3,selectInput(ns("damage_type"),"Damage type",enemy_damage_types())),column(3,selectInput(ns("material"),"Attack source",enemy_materials()))),
    fluidRow(column(3,selectInput(ns("kind"),"Kind",c("Natural"="natural","Magical"="magical","Tactical"="tactical","Special"="special"))),column(3,selectInput(ns("action"),"Economy",c("Action"="action","Bonus action"="bonus","Reaction"="reaction","Passive"="passive"))),column(3,numericInput(ns("range_ft"),"Range",5,min=0)),column(3,numericInput(ns("long_range_ft"),"Long range",5,min=0))),
    fluidRow(column(3,selectInput(ns("ability"),"Statistic",c("STR"="str","DEX"="dex","Blood Strength"="bld_str"))),column(3,selectInput(ns("rarity"),"Rarity",c("Core"="core","Uncommon"="uncommon","Elite"="elite","Boss"="boss"))),column(3,selectInput(ns("lore_status"),"Lore status",c("Canonical"="canonical","Mechanically inferred"="mechanically_inferred","Provisional"="provisional"))),column(3,textInput(ns("usage"),"Usage","unlimited"))),
    fluidRow(column(4,textInput(ns("requires"),"Requirement")),column(4,selectInput(ns("on_hit_condition"),"On-hit condition",c("None"="",enemy_conditions(),"Slowed"="slowed","Distracted"="distracted","Healing blocked"="healing_blocked"))),column(2,numericInput(ns("push_ft"),"Push ft",0,min=0)),column(2,numericInput(ns("heal_fraction"),"Heal fraction",0,min=0,max=1,step=.25))),
    textInput(ns("description"),"Description"),actionButton(ns("save_attack"),"Save Attack",class="btn btn-primary"))))}

controlNpcAttacksServer<-function(id){moduleServer(id,function(input,output,session){`%||%`<-get("%||%",inherits=TRUE);path<-file.path("control_app","data","npc_attacks.rds");inv_path<-file.path("control_app","data","control_inventory.rds");dir.create(dirname(path),recursive=TRUE,showWarnings=FALSE)
  seed<-lapply(names(enemy_attack_catalog()),function(k){x<-enemy_attack_catalog()[[k]];x$id<-k;x$description<-x$desc%||%"";x});seed<-Filter(function(a)!nzchar(as.character(a$loot_id%||%"")),seed); attacks<-reactiveVal({x<-if(file.exists(path))tryCatch(readRDS(path),error=function(e)list())else list();x<-Filter(function(a)!nzchar(as.character(a$loot_id%||%"")),x);if(length(x))x else seed}); active<-reactive({x<-Filter(function(a)identical(a$id,input$attack_id%||%""),attacks());if(length(x))x[[1]]else NULL})
  observe({x<-attacks();vals<-vapply(x,`[[`,"","id");keep<-isolate(input$attack_id%||%"");updateSelectInput(session,"attack_id",choices=setNames(vals,vapply(x,`[[`,"","name")),selected=if(keep%in%vals)keep else vals[1])})
  observeEvent(input$attack_id,{x<-active();if(is.null(x))return();updateTextInput(session,"name",value=x$name);updateNumericInput(session,"hit",value=x$hit);updateTextInput(session,"damage",value=x$dmg);updateSelectInput(session,"damage_type",selected=x$type);updateSelectInput(session,"material",selected=x$material);for(field in c("kind","action","ability","rarity","lore_status"))updateSelectInput(session,field,selected=x[[field]]%||%switch(field,kind="natural",action="action",ability="str",rarity="core",lore_status="canonical"));updateNumericInput(session,"range_ft",value=x$range_ft%||%5);updateNumericInput(session,"long_range_ft",value=x$long_range_ft%||%x$range_ft%||%5);updateTextInput(session,"usage",value=x$usage%||%"unlimited");updateTextInput(session,"requires",value=x$requires%||%"");updateSelectInput(session,"on_hit_condition",selected=x$on_hit_condition%||%"");updateNumericInput(session,"push_ft",value=x$push_ft%||%0);updateNumericInput(session,"heal_fraction",value=x$heal_fraction%||%0);updateTextInput(session,"description",value=x$description%||%x$desc%||%"")},ignoreInit=TRUE)
  save_all<-function(x){attacks(x);saveRDS(x,path)};observeEvent(input$new_attack,{x<-attacks();id<-paste0("attack_",as.integer(Sys.time()));x<-c(x,list(list(id=id,name="New Attack",hit=2,dmg="1d6",type="slashing",material="natural",loot_id="",description="")));save_all(x);updateSelectInput(session,"attack_id",selected=id)})
  observeEvent(input$save_attack,{x<-attacks();i<-which(vapply(x,function(a)identical(a$id,input$attack_id),logical(1)))[1];if(is.na(i))return();x[[i]]<-list(id=x[[i]]$id,name=trimws(input$name%||%"Attack"),hit=as.integer(input$hit%||%0),dmg=input$damage%||%"1d6",type=input$damage_type%||%"slashing",material=input$material%||%"natural",loot_id="",kind=input$kind%||%"natural",action=input$action%||%"action",range_ft=as.integer(input$range_ft%||%5),long_range_ft=as.integer(input$long_range_ft%||%input$range_ft%||%5),ability=input$ability%||%"str",rarity=input$rarity%||%"core",lore_status=input$lore_status%||%"canonical",usage=input$usage%||%"unlimited",requires=input$requires%||%"",on_hit_condition=input$on_hit_condition%||%"",push_ft=as.integer(input$push_ft%||%0),heal_fraction=as.numeric(input$heal_fraction%||%0),description=input$description%||%"");save_all(x);showNotification("Attack saved.")})
})}
