controlStoryUI<-function(id){ns<-NS(id);tagList(
  div(class="control-card",div(class="control-section-title","📜 Storyboard Builder"),p(class="control-mini","Pictures remain local. Export the finished ZIP and send the same bundle to your players."),fluidRow(column(5,textInput(ns("board_title"),"Storyboard title","New Adventure")),column(4,selectInput(ns("local_board"),"Saved local storyboard",choices=character())),column(3,br(),actionButton(ns("new_board"),"New",class="btn btn-default"),actionButton(ns("load_board"),"Load",class="btn btn-primary"))),tags$hr(),h4("Add or edit a scene"),fluidRow(column(4,textInput(ns("slide_title"),"Scene title","A New Scene")),column(4,fileInput(ns("slide_image"),"Picture (stored locally)",accept=c("image/png","image/jpeg","image/gif","image/webp")),uiOutput(ns("image_status"))),column(4,selectInput(ns("edit_slide"),"Scene to edit",choices=c("New scene"="new")))),textAreaInput(ns("slide_text"),"Narration / story text","",rows=5),actionButton(ns("save_slide"),"Add Scene",class="btn btn-success"),actionButton(ns("delete_slide"),"Delete Selected",class="btn btn-danger"),downloadButton(ns("export_board"),"Export Storyboard ZIP"),tags$hr(),uiOutput(ns("slides_ui"))),
  div(class="control-card",div(class="control-section-title","Live Story Control"),p(class="control-mini","Players only receive the scene number after you reveal it here."),uiOutput(ns("live_summary")),fluidRow(column(5,selectInput(ns("live_slide"),"Scene to reveal",choices=character())),column(7,br(),actionButton(ns("reveal"),"Reveal Selected",class="btn btn-primary"),actionButton(ns("previous"),"← Previous"),actionButton(ns("next_scene"),"Next →",class="btn btn-success"))),tags$hr(),uiOutput(ns("preview")))
)}

controlStoryServer<-function(id,ctrl){moduleServer(id,function(input,output,session){
  board<-reactiveVal(NULL);rev<-reactiveVal(0L);pending_image<-reactiveVal("");image_message<-reactiveVal("No picture selected.")
  refresh_choices<-function(selected=NULL){choices<-storyboard_list_local();updateSelectInput(session,"local_board",choices=choices,selected=selected%||%if(length(choices))unname(choices[[1L]])else character())}
  observeEvent(TRUE,refresh_choices(),once=TRUE)
  save_board<-function(x){x<-storyboard_write(x);board(x);rev(rev()+1L);refresh_choices(x$storyboard_id);labels<-vapply(seq_along(x$slides),function(i)paste(i,x$slides[[i]]$title%||%"Untitled"),character(1));updateSelectInput(session,"edit_slide",choices=c("New scene"="new",stats::setNames(seq_along(x$slides),labels)),selected="new");updateSelectInput(session,"live_slide",choices=stats::setNames(seq_along(x$slides),labels));x}
  observeEvent(input$new_board,{title<-trimws(input$board_title%||%"New Adventure");x<-list(storyboard_id=paste0(story_safe_id(title),"-",format(Sys.time(),"%Y%m%d%H%M%S")),title=title,slides=list());tryCatch({save_board(x);showNotification("New local storyboard created.")},error=function(e)showNotification(paste("Storyboard could not be created:",conditionMessage(e)),type="error",duration=10))},ignoreInit=TRUE)
  observeEvent(input$load_board,{req(input$local_board);x<-storyboard_read(input$local_board);if(is.null(x))return(showNotification("Storyboard could not be loaded.",type="error"));board(x);updateTextInput(session,"board_title",value=x$title);save_board(x)},ignoreInit=TRUE)
  observeEvent(input$edit_slide,{x<-board();idx<-suppressWarnings(as.integer(input$edit_slide));if(is.null(x)||is.na(idx)||idx<1||idx>length(x$slides)){pending_image("");image_message("No picture selected.");updateActionButton(session,"save_slide",label="Add Scene");return()};s<-x$slides[[idx]];pending_image(as.character(s$image%||%""));image_message(if(nzchar(pending_image()))"Existing scene picture will be kept unless replaced."else"This scene has no picture.");updateTextInput(session,"slide_title",value=s$title%||%"");updateTextAreaInput(session,"slide_text",value=s$text%||%"");updateActionButton(session,"save_slide",label="Save Scene")},ignoreInit=TRUE)
  observeEvent(input$slide_image,{req(input$slide_image$datapath);x<-board();if(is.null(x))return(showNotification("Create or load a storyboard before choosing a picture.",type="warning"));image_message("Copying picture…");path<-tryCatch(storyboard_copy_image(x$storyboard_id,input$slide_image$datapath,input$slide_image$name),error=function(e){showNotification(e$message,type="error",duration=10);""});pending_image(path);image_message(if(nzchar(path))paste0("✓ Picture attached: ",input$slide_image$name)else"Picture was not attached.")},ignoreInit=TRUE)
  output$image_status<-renderUI({image_message();tags$small(style=if(nzchar(pending_image()))"color:#276738;font-weight:bold"else"opacity:.7",image_message())})
  observeEvent(input$save_slide,{x<-board();if(is.null(x))return(showNotification("Create or load a storyboard first.",type="warning"));idx<-suppressWarnings(as.integer(input$edit_slide));existing<-if(!is.na(idx)&&idx>=1&&idx<=length(x$slides))x$slides[[idx]]else list();image<-as.character(pending_image()%||%existing$image%||%"");slide<-list(id=as.character(existing$id%||%paste0("slide-",length(x$slides)+1L)),title=trimws(input$slide_title%||%"Untitled Scene"),text=as.character(input$slide_text%||%""),image=image);if(is.na(idx))x$slides[[length(x$slides)+1L]]<-slide else x$slides[[idx]]<-slide;x$title<-trimws(input$board_title%||%x$title);save_board(x);pending_image("");image_message("No picture selected.");updateTextInput(session,"slide_title",value="A New Scene");updateTextAreaInput(session,"slide_text",value="");showNotification(if(nzchar(image))"Scene and picture saved locally."else"Scene saved locally (no picture attached).")},ignoreInit=TRUE)
  observeEvent(input$delete_slide,{x<-board();idx<-suppressWarnings(as.integer(input$edit_slide));if(is.null(x)||is.na(idx)||idx<1||idx>length(x$slides))return(showNotification("Choose a scene to delete.",type="warning"));x$slides<-x$slides[-idx];save_board(x);showNotification("Scene deleted.")},ignoreInit=TRUE)
  output$slides_ui<-renderUI({rev();x<-board();if(is.null(x)||!length(x$slides))return(tags$em("No scenes yet."));tagList(h4(x$title),lapply(seq_along(x$slides),function(i){s<-x$slides[[i]];div(style="border:1px solid rgba(191,167,111,.55);border-radius:10px;padding:10px;margin:8px 0",strong(paste(i,s$title%||%"Untitled")),p(style="white-space:pre-wrap;margin:6px 0",s$text%||%""),if(nzchar(as.character(s$image%||%"")))span(class="control-kpi","Picture attached")else span(class="control-mini","Text only"))}))})
  output$export_board<-downloadHandler(filename=function(){x<-board();paste0(story_safe_id(x$title%||%"storyboard"),".zip")},content=function(file){x<-board();req(!is.null(x),length(x$slides)>0);dir<-storyboard_path(x$storyboard_id);old<-getwd();on.exit(setwd(old),add=TRUE);setwd(dir);files<-c("manifest.json",list.files("assets",recursive=TRUE,full.names=TRUE));utils::zip(file,files=files,flags="-r9X")},contentType="application/zip")
  live_row<-reactive({ctrl$refresh_key;sid<-suppressWarnings(as.integer(ctrl$session_id%||%NA));if(is.na(sid))data.frame()else get_session_story_state(sid)})
  reveal_slide<-function(index){x<-board();sid<-suppressWarnings(as.integer(ctrl$session_id%||%NA));if(is.null(x)||!length(x$slides))return(showNotification("Load a storyboard with at least one scene.",type="warning"));if(is.na(sid))return(showNotification("Select an active session first.",type="warning"));idx<-max(1L,min(length(x$slides),as.integer(index)));row<-set_session_story_state(sid,x$storyboard_id,x$title,idx);if(is.null(row))return(showNotification("Scene could not be revealed.",type="error"));ctrl$refresh_key<-as.integer(ctrl$refresh_key%||%0L)+1L;updateSelectInput(session,"live_slide",selected=as.character(idx));showNotification(paste("Scene",idx,"is now visible to players."),type="message")}
  observeEvent(input$reveal,{req(input$live_slide);reveal_slide(input$live_slide)},ignoreInit=TRUE)
  observeEvent(input$previous,{r<-live_row();reveal_slide(if(nrow(r))as.integer(r$current_slide[[1L]])-1L else 1L)},ignoreInit=TRUE)
  observeEvent(input$next_scene,{r<-live_row();reveal_slide(if(nrow(r))as.integer(r$current_slide[[1L]])+1L else 1L)},ignoreInit=TRUE)
  output$live_summary<-renderUI({r<-live_row();if(!nrow(r))return(p("No storyboard is active for this session."));span(class="control-kpi",paste0(r$title[[1L]]," · Scene ",r$current_slide[[1L]]," · revision ",r$revision[[1L]]))})
  output$preview<-renderUI({rev();x<-board();if(is.null(x)||!length(x$slides))return(NULL);idx<-suppressWarnings(as.integer(input$live_slide%||%1L));idx<-max(1L,min(length(x$slides),ifelse(is.na(idx),1L,idx)));s<-x$slides[[idx]];prefix<-paste0("story-control-",story_safe_id(x$storyboard_id));suppressWarnings(try(shiny::removeResourcePath(prefix),silent=TRUE));shiny::addResourcePath(prefix,storyboard_path(x$storyboard_id));image<-as.character(s$image%||%"");tagList(h3(s$title%||%"Untitled"),if(nzchar(image))tags$img(src=paste0("/",prefix,"/",gsub("\\\\","/",image)),style="display:block;max-width:100%;max-height:55vh;margin:0 auto 14px;border-radius:12px;box-shadow:0 8px 24px rgba(0,0,0,.25)")else div(class="control-mini",style="padding:18px;border:1px dashed #bfa76f;text-align:center","This scene has no picture attached."),p(style="white-space:pre-wrap;font-family:Georgia,serif;font-size:16px",s$text%||%""))})
})}
