library(shiny)

controlNpcAttacksUI<-function(id){ns<-NS(id);div(class="control-card",div(class="control-section-title","NPC Natural / Special Attack Designer"),p(class="control-mini","Weapons come from Control Inventory and automatically become attacks. Use this editor only for claws, bites, breath, magic and other non-weapon attacks."),fluidRow(
  column(4,selectInput(ns("attack_id"),"Attack",choices=character()),textInput(ns("name"),"Name"),actionButton(ns("new_attack"),"New Attack")),
  column(8,fluidRow(column(3,numericInput(ns("hit"),"Hit bonus",2)),column(3,textInput(ns("damage"),"Damage","1d6")),column(3,selectInput(ns("damage_type"),"Damage type",enemy_damage_types())),column(3,selectInput(ns("material"),"Attack source",enemy_materials()))),textInput(ns("description"),"Description"),actionButton(ns("save_attack"),"Save Attack",class="btn btn-primary"))))}

controlNpcAttacksServer<-function(id){moduleServer(id,function(input,output,session){`%||%`<-get("%||%",inherits=TRUE);path<-file.path("control_app","data","npc_attacks.rds");inv_path<-file.path("control_app","data","control_inventory.rds");dir.create(dirname(path),recursive=TRUE,showWarnings=FALSE)
  seed<-lapply(names(enemy_attack_catalog()),function(k){x<-enemy_attack_catalog()[[k]];x$id<-k;x$description<-x$desc%||%"";x});seed<-Filter(function(a)!nzchar(as.character(a$loot_id%||%"")),seed); attacks<-reactiveVal({x<-if(file.exists(path))tryCatch(readRDS(path),error=function(e)list())else list();x<-Filter(function(a)!nzchar(as.character(a$loot_id%||%"")),x);if(length(x))x else seed}); active<-reactive({x<-Filter(function(a)identical(a$id,input$attack_id%||%""),attacks());if(length(x))x[[1]]else NULL})
  observe({x<-attacks();vals<-vapply(x,`[[`,"","id");keep<-isolate(input$attack_id%||%"");updateSelectInput(session,"attack_id",choices=setNames(vals,vapply(x,`[[`,"","name")),selected=if(keep%in%vals)keep else vals[1])})
  observeEvent(input$attack_id,{x<-active();if(is.null(x))return();updateTextInput(session,"name",value=x$name);updateNumericInput(session,"hit",value=x$hit);updateTextInput(session,"damage",value=x$dmg);updateSelectInput(session,"damage_type",selected=x$type);updateSelectInput(session,"material",selected=x$material);updateTextInput(session,"description",value=x$description%||%"")},ignoreInit=TRUE)
  save_all<-function(x){attacks(x);saveRDS(x,path)};observeEvent(input$new_attack,{x<-attacks();id<-paste0("attack_",as.integer(Sys.time()));x<-c(x,list(list(id=id,name="New Attack",hit=2,dmg="1d6",type="slashing",material="natural",loot_id="",description="")));save_all(x);updateSelectInput(session,"attack_id",selected=id)})
  observeEvent(input$save_attack,{x<-attacks();i<-which(vapply(x,function(a)identical(a$id,input$attack_id),logical(1)))[1];if(is.na(i))return();x[[i]]<-list(id=x[[i]]$id,name=trimws(input$name%||%"Attack"),hit=as.integer(input$hit%||%0),dmg=input$damage%||%"1d6",type=input$damage_type%||%"slashing",material=input$material%||%"natural",loot_id="",description=input$description%||%"");save_all(x);showNotification("Attack saved.")})
})}
