library(shiny)

controlMerchantsUI<-function(id){ns<-NS(id);tagList(
  div(class="control-card",div(class="control-section-title","Merchant Generator"),p(class="control-mini","Generate persistent merchant stock from the Control catalogue, inspect it, then invite players in the active session."),
    fluidRow(column(3,textInput(ns("name"),"Merchant name","Travelling Merchant")),column(3,selectInput(ns("wealth"),"Merchant class",c("Poor"="poor","Moderate"="moderate","Rich"="rich"))),column(3,selectInput(ns("specialty"),"Stock",c("General goods"="general","Livestock & mounts"="livestock","Provisions & travel"="provisions","Food seller"="food","Weapons dealer"="weapons","Armourer"="armour","Hunter & ranger"="hunter","Apothecary"="apothecary","Arcane curios"="arcane","Outfitter"="outfitter","Luxury goods"="luxury","Blacksmith"="smith","Materials & tools"="materials"))),column(3,selectInput(ns("temperament"),"Haggling",c("Fair"="fair","Hard haggler"="hard","Generous"="generous")))),
    actionButton(ns("generate"),"Generate Stock",class="btn btn-primary"),actionButton(ns("save"),"Save Merchant",class="btn btn-success"),br(),br(),uiOutput(ns("summary")),DT::DTOutput(ns("preview"))),
  div(class="control-card",div(class="control-section-title","Open Merchant for Players"),selectInput(ns("merchant_id"),"Saved merchant",choices=character()),uiOutput(ns("saved_summary")),DT::DTOutput(ns("saved_stock")),div(class="merchant-invite-panel",checkboxGroupInput(ns("players"),"Choose players to invite",choices=character()),div(class="merchant-invite-actions",actionButton(ns("invite"),"Send Merchant Invitation",class="btn btn-success"),actionButton(ns("close"),"Close Merchant",class="btn btn-default"))))
)}

controlMerchantsServer<-function(id,ctrl,players_tbl,bump_refresh=NULL){moduleServer(id,function(input,output,session){`%||%`<-get("%||%",inherits=TRUE);draft<-reactiveVal(NULL);saved_rev<-reactiveVal(0L)
  catalogue<-function(){base<-lapply(names(enemy_loot_catalog()),function(id){x<-enemy_loot_catalog()[[id]];x$id<-id;x});db<-get_control_catalogue_definitions();path<-file.path("control_app","data","control_inventory.rds");local<-if(file.exists(path))tryCatch(readRDS(path),error=function(e)list())else list();all<-c(local,db,base);seen<-character();Filter(function(x){id<-as.character(x$id%||%"");keep<-nzchar(id)&&!id%in%seen;seen<<-c(seen,id);keep},all)}
  eligible<-function(items,specialty){Filter(function(x){typ<-tolower(as.character(x$type%||%"item"));category<-tolower(as.character((x$meta%||%list())$category%||%""));pools<-tolower(as.character(x$pools%||%character()));nm<-tolower(as.character(x$name%||%""));switch(specialty,general=typ!="animal",livestock=typ=="animal",provisions=category%in%c("food","mundane_loot","tool"),food=category=="food",weapons=typ=="weapon",armour=typ%in%c("armor","armour"),hunter=typ!="animal"&&(any(pools%in%c("hunter","ranger","animal"))||grepl("bow|arrow|trap|pelt|knife|jerky|ration",nm)),apothecary=category%in%c("consumable","magical_item")||grepl("draught|potion|herb|remedy|poison",nm),arcane=category%in%c("magical_item","crafting")||grepl("glyph|scroll|crystal|dust",nm),outfitter=category%in%c("mundane_loot","tool")||typ%in%c("armor","armour"),luxury=category%in%c("treasure","magical_item")||as.numeric(x$value%||%0)>=25,smith=typ%in%c("weapon","armor","armour"),materials=category%in%c("crafting","tool"),FALSE)},items)}
  generate<-function(){wealth<-input$wealth%||%"moderate";specialty<-input$specialty%||%"general";pool<-eligible(catalogue(),specialty);if(!length(pool))pool<-catalogue();n<-c(poor=4L,moderate=8L,rich=14L)[[wealth]];chosen<-merchant_select_stock(pool,min(n,length(pool)),specialty);chosen<-lapply(chosen,function(item){item$catalogue_id<-item$id;item$qty<-if((item$type%||%"")%in%c("consumable","item"))sample(1:5,1)else 1L;rolled<-roll_loot_equipment_provenance(list(item),enemy_type=if(wealth=="rich")"Boss"else"Merchant",characteristics=character());rolled[[1L]]});list(name=trimws(input$name%||%"Merchant"),wealth=wealth,specialty=specialty,temperament=input$temperament%||%"fair",gold=c(poor=15,moderate=75,rich=250)[[wealth]],stock=chosen)}
  observeEvent(input$generate,{draft(generate())},ignoreInit=TRUE)
  output$summary<-renderUI({d<-draft();if(is.null(d))return(p("Generate stock to preview it."));p(strong(d$name)," · ",tools::toTitleCase(d$wealth)," · ",tools::toTitleCase(d$specialty)," · ",d$gold," gold · ",length(d$stock)," stock lines")})
  output$preview<-DT::renderDT({d<-draft();if(is.null(d)||!length(d$stock))return(NULL);df<-do.call(rbind,lapply(d$stock,function(x){m<-x$meta%||%list();data.frame(Item=x$name%||%"Item",Type=x$type%||%"item",Quantity=x$qty%||%1,Value=x$value%||%0,Material=m$material%||%"—",Quality=m$build_quality%||%"—")}));DT::datatable(df,rownames=FALSE,options=list(dom="t",scrollX=TRUE))})
  refresh_merchants<-function(){saved_rev(isolate(saved_rev())+1L)}
  observe({saved_rev();sid<-suppressWarnings(as.integer(ctrl$session_id%||%NA));m<-if(!is.na(sid))list_session_merchants(sid,TRUE)else data.frame();choices<-if(nrow(m))setNames(as.character(m$id),paste0(m$name," · ",m$gold,"g"))else character();updateSelectInput(session,"merchant_id",choices=choices)})
  selected_bundle<-reactive({saved_rev();mid<-suppressWarnings(as.integer(input$merchant_id%||%NA));if(is.na(mid))NULL else get_merchant_bundle(mid)})
  output$saved_summary<-renderUI({b<-selected_bundle();if(is.null(b))return(NULL);m<-b$merchant;p(strong(m$name[[1L]])," · ",tools::toTitleCase(m$wealth_class[[1L]])," · ",tools::toTitleCase(m$temperament[[1L]])," · purse ",m$gold[[1L]],"g")})
  output$saved_stock<-DT::renderDT({b<-selected_bundle();if(is.null(b)||!nrow(b$stock))return(NULL);s<-b$stock;df<-do.call(rbind,lapply(seq_len(nrow(s)),function(i){item<-enemy_db_json(s$item_json[[i]],list());m<-item$meta%||%list();data.frame(Item=item$name%||%"Item",Quantity=s$quantity[[i]],BaseValue=s$base_value[[i]],Material=m$material%||%"—",Quality=m$build_quality%||%"—")}));DT::datatable(df,rownames=FALSE,options=list(dom="t",scrollX=TRUE))})
  observe({p<-players_tbl();if(!is.data.frame(p)||!nrow(p))return(updateCheckboxGroupInput(session,"players",choices=character()));ids<-as.character(p$character_id);labels<-as.character(p$display_name%||%p$char_name%||%ids);updateCheckboxGroupInput(session,"players",choices=setNames(ids,labels),selected=intersect(isolate(input$players%||%character()),ids))})
  observeEvent(input$save,{d<-draft();sid<-suppressWarnings(as.integer(ctrl$session_id%||%NA));if(is.null(d)||is.na(sid))return(showNotification("Generate stock and select a session first.",type="error"));m<-create_merchant(sid,d$name,d$wealth,d$specialty,d$temperament,d$gold,d$stock);if(is.null(m))return(showNotification("Merchant could not be saved.",type="error"));refresh_merchants();updateSelectInput(session,"merchant_id",selected=as.character(m$id[[1L]]));showNotification("Merchant saved and ready to invite.",type="message")},ignoreInit=TRUE)
  observeEvent(input$invite,{mid<-suppressWarnings(as.integer(input$merchant_id));ids<-as.character(input$players%||%character());if(is.na(mid)||!length(ids))return(showNotification("Choose a merchant and at least one player.",type="warning"));if(!invite_players_to_merchant(mid,ids))return(showNotification("Invitations could not be sent.",type="error"));showNotification("Merchant invitations sent.",type="message")},ignoreInit=TRUE)
  observeEvent(input$close,{mid<-suppressWarnings(as.integer(input$merchant_id));if(is.na(mid))return();con<-get_db_connection();if(is.null(con))return();on.exit(release_db_connection(con),add=TRUE);DBI::dbExecute(con,"UPDATE merchants SET status='closed',updated_at=now() WHERE id=$1",params=list(mid));refresh_merchants();showNotification("Merchant closed.")},ignoreInit=TRUE)
})}
