library(shiny)

controlQuestsUI<-function(id){ns<-NS(id);tagList(
  tags$style(HTML(paste0("#",ns("quest_editor")," input, #",ns("quest_editor")," textarea, #",ns("quest_editor")," select{font-family:Georgia,serif;text-transform:none;} #",ns("quest_editor")," label{text-transform:none;}"))),
  div(id=ns("quest_editor"),class="control-card",div(class="control-section-title","✦ Party Quests"),p("Create a shared journal for the active party. Completed and failed quests remain in the players' journal; Hidden quests are visible only here."),
    div(class="row",div(class="col-md-4",selectInput(ns("quest_id"),"Quest",choices=c()),div(style="display:flex;gap:8px;flex-wrap:wrap",actionButton(ns("edit_quest"),"Edit Selected",class="btn btn-primary"),actionButton(ns("new_quest"),"New Quest",class="btn btn-default"))),div(class="col-md-8",textInput(ns("title"),"Title",placeholder="A Blade in the Dark"),textAreaInput(ns("description"),"Description",rows=6,placeholder="Describe the story, its stakes and what the party knows…"),selectInput(ns("status"),"Status",choices=c("Active"="active","Completed"="completed","Failed"="failed","Hidden from players"="hidden")),actionButton(ns("save"),"Save Quest",class="btn btn-primary")))),
  div(class="control-card",div(class="control-section-title","Objectives"),textInput(ns("objective_text"),"New objective",placeholder="Find a way into the ruined watchtower"),actionButton(ns("add_objective"),"Add Objective",class="btn btn-success"),uiOutput(ns("objectives_ui")))
)}

controlQuestsServer<-function(id,session_id){moduleServer(id,function(input,output,session){
  `%||%`<-get("%||%",inherits=TRUE);rev<-reactiveVal(0L);editing<-reactiveVal(NA_integer_);restoring<-reactiveVal(FALSE)
  sid<-reactive(suppressWarnings(as.integer(session_id()%||%NA)))
  quests<-reactive({rev();if(is.na(sid()))return(data.frame());list_party_quests(sid(),TRUE)})
  observe({q<-quests();choices<-if(nrow(q))setNames(as.character(q$id),paste0(q$title," · ",tools::toTitleCase(q$status)))else c();selected<-as.character(editing());if(!selected%in%unname(choices))selected<-if(length(choices))unname(choices[[1L]])else character();updateSelectInput(session,"quest_id",choices=choices,selected=selected)})
  load_quest<-function(id){bundle<-get_party_quest(id);if(is.null(bundle))return();q<-bundle$quest;editing(as.integer(q$id[[1L]]));restoring(TRUE);updateTextInput(session,"title",value=q$title[[1L]]);updateTextAreaInput(session,"description",value=q$description[[1L]]);updateSelectInput(session,"status",selected=q$status[[1L]]);session$onFlushed(function()restoring(FALSE),once=TRUE)}
  observeEvent(input$quest_id,{if(!isTRUE(restoring())&&nzchar(input$quest_id%||%""))load_quest(input$quest_id)},ignoreInit=TRUE)
  observeEvent(input$edit_quest,{if(!nzchar(input$quest_id%||%""))return(showNotification("Choose a quest to edit first.",type="warning"));load_quest(input$quest_id);showNotification("Quest loaded for editing.",type="message")},ignoreInit=TRUE)
  observeEvent(input$new_quest,{editing(NA_integer_);updateSelectInput(session,"quest_id",selected=character());updateTextInput(session,"title",value="");updateTextAreaInput(session,"description",value="");updateSelectInput(session,"status",selected="active")},ignoreInit=TRUE)
  observeEvent(input$save,{if(is.na(sid()))return(showNotification("Choose an active session first.",type="error"));saved<-save_party_quest(sid(),input$title,input$description,input$status,editing());if(is.null(saved)||!nrow(saved))return(showNotification("Quest could not be saved. Add a title and try again.",type="error"));editing(as.integer(saved$id[[1L]]));rev(rev()+1L);showNotification("Party quest saved.",type="message")},ignoreInit=TRUE)
  output$objectives_ui<-renderUI({rev();qid<-editing();if(is.na(qid))return(p(style="margin-top:12px","Save the quest before adding objectives."));b<-get_party_quest(qid);if(is.null(b)||!nrow(b$objectives))return(p(style="margin-top:12px",em("No objectives yet.")));tagList(lapply(seq_len(nrow(b$objectives)),function(i){o<-b$objectives[i,,drop=FALSE];div(style="display:flex;gap:8px;align-items:center;margin-top:8px;padding:8px;border:1px solid #c4a66b;border-radius:8px",tags$button(type="button",class=paste("btn",if(isTRUE(o$is_complete[[1L]]))"btn-success"else"btn-default"),onclick=sprintf("Shiny.setInputValue('%s',{id:%d,complete:%s,nonce:Math.random()},{priority:'event'})",session$ns("toggle_objective"),as.integer(o$id[[1L]]),if(isTRUE(o$is_complete[[1L]]))"false"else"true"),if(isTRUE(o$is_complete[[1L]]))"✓"else"◇"),span(style=paste0("flex:1",if(isTRUE(o$is_complete[[1L]]))";text-decoration:line-through;opacity:.65"else""),o$objective_text[[1L]]),tags$button(type="button",class="btn btn-danger",onclick=sprintf("Shiny.setInputValue('%s',%d,{priority:'event'})",session$ns("remove_objective"),as.integer(o$id[[1L]])),"×"))}))})
  observeEvent(input$add_objective,{qid<-editing();if(is.na(qid))return(showNotification("Save the quest first.",type="warning"));if(is.null(add_party_quest_objective(qid,input$objective_text)))return(showNotification("Enter an objective before adding it.",type="error"));updateTextInput(session,"objective_text",value="");rev(rev()+1L)},ignoreInit=TRUE)
  observeEvent(input$toggle_objective,{if(set_party_quest_objective(input$toggle_objective$id,isTRUE(input$toggle_objective$complete)))rev(rev()+1L)},ignoreInit=TRUE)
  observeEvent(input$remove_objective,{id<-as.integer(input$remove_objective);showModal(modalDialog(title="Remove objective?",p("This permanently removes the objective from the party journal."),footer=tagList(modalButton("Cancel"),actionButton(session$ns("confirm_remove_objective"),"Remove",class="btn btn-danger"))));session$userData$remove_objective_id<-id},ignoreInit=TRUE)
  observeEvent(input$confirm_remove_objective,{id<-session$userData$remove_objective_id;session$userData$remove_objective_id<-NULL;removeModal();if(!is.null(id)&&remove_party_quest_objective(id))rev(rev()+1L)},ignoreInit=TRUE)
})}
