library(shiny)

chestUI<-function(id){ns<-NS(id);tagList(tags$style(HTML(paste0("#",ns("wrap"),"{position:fixed;right:22px;bottom:234px;z-index:1039}#",ns("open"),"{width:58px;height:58px;border-radius:50%;font-size:25px;background:#745128;color:#fff1c7;border:2px solid #d7b96d;box-shadow:0 5px 18px rgba(0,0,0,.4)}#",ns("badge"),"{position:absolute;right:-3px;top:-5px;background:#8f241d;color:#fff;border-radius:999px;min-width:22px;padding:2px 6px;text-align:center;font-weight:bold}.drachuri-lock{background:radial-gradient(circle,#80613c 0 13%,#342315 14% 24%,#b28a50 25% 29%,#24170e 30% 100%);border:9px ridge #80613c;border-radius:50%;width:330px;height:330px;max-width:75vw;margin:12px auto;position:relative;box-shadow:inset 0 0 35px #000,0 8px 25px #0008}.drachuri-lock:after{content:'';position:absolute;width:18px;height:128px;background:linear-gradient(90deg,#6f5230,#e2c47e,#50371e);left:calc(50% - 9px);top:18px;transform-origin:50% 147px;transform:rotate(var(--pick-angle,0deg));border-radius:8px 8px 2px 2px}.lock-turn{height:12px;background:#20150d;border:1px solid #bc9458;border-radius:10px;overflow:hidden}.lock-turn span{display:block;height:100%;background:linear-gradient(90deg,#8b3027,#d7b96d);width:var(--turn,0%);transition:width .3s}.chest-loot-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:10px;max-height:50vh;overflow:auto}.chest-loot{border:1px solid #b99a5d;border-radius:12px;background:#fffdf5;padding:12px}"))),div(id=ns("wrap"),actionButton(ns("open"),"▣",title="Chests"),uiOutput(ns("badge"))))}

chestServer<-function(id,state){moduleServer(id,function(input,output,session){`%||%`<-get("%||%",inherits=TRUE);poll<-reactiveTimer(2500,session);rev<-reactiveVal(0L);active<-reactiveVal(NA_integer_);prompted<-reactiveVal(integer());feedback<-reactiveVal(NULL)
  cid<-reactive({x<-state$char_id;if(is.null(x)||!length(x)||is.na(x[[1L]]))""else as.character(x[[1L]])})
  invitations<-reactive({poll();rev();if(!nzchar(cid())||isTRUE(state$offline_mode))return(data.frame());get_character_chests(cid(),FALSE)})
  output$badge<-renderUI({n<-sum(invitations()$status=="pending");if(n>0)span(n)})
  sleight_profile<-function(chest_id=active()){char<-validate_character(state$char);rank<-as.character(char$prof$skills$sleight_of_hand%||%char$prof$skills$`Sleight of Hand`%||%"None");cards<-tolower(character_skill_cards(char,"sleight of hand"));dex<-floor((as.integer(char$abilities$dex%||%10L)-10L)/2L);bonus<-max(-3,min(6,dex))*1.5+if(rank=="Expertise")12 else if(rank=="Proficient")6 else 0;if("reliable"%in%cards)bonus<-bonus+4;if("inspired"%in%cards)bonus<-bonus+2;wild_note<-"";if("wild_card"%in%cards){seed<-sum(utf8ToInt(paste0(cid(),":",chest_id)));wild_good<-seed%%2L==0L;bonus<-bonus+if(wild_good)8 else-4;wild_note<-if(wild_good)"Wild Card: this lock feels unusually forgiving."else"Wild Card: this lock feels unusually temperamental."};items<-inventory_normalize(char$inventory$items);loose<-sum(as.integer(items$qty[grepl("lockpick|lock pick",tolower(items$name))&!grepl("tools",tolower(items$name))]),na.rm=TRUE);kits<-which(grepl("thieves.? tools",tolower(items$name)));kit_picks<-sum(vapply(kits,function(i)as.integer((items$meta[[i]]%||%list())$lockpicks_remaining%||%10L),integer(1)));list(rank=rank,cards=cards,tolerance_bonus=bonus,feedback_bonus=if("inspired"%in%cards)18 else if(rank=="Expertise")12 else if(rank=="Proficient")6 else 0,wild_note=wild_note,pick_note=paste0(loose+kit_picks," lockpick",if(loose+kit_picks==1L)""else"s"," available"))}
  open_chest<-function(id){id<-as.integer(id);b<-get_chest_bundle(id);if(is.null(b))return(showNotification("That chest is no longer available.",type="warning"));active(id);mark_chest_invitation(id,cid(),"opened");session$userData$pending_chest_id<-id;feedback(NULL);rev(rev()+1L);showModal(modalDialog(size="l",title=b$chest$name[[1L]],uiOutput(session$ns("body")),footer=tagList(actionButton(session$ns("leave"),"Leave Chest"))))}
  output$body<-renderUI({rev();id<-active();if(is.na(id))return(NULL);b<-get_chest_bundle(id);if(is.null(b))return(p("Chest unavailable."));ch<-b$chest;if(isTRUE(ch$locked[[1L]])){profile<-sleight_profile(id);f<-feedback();return(tagList(h3("A ",tools::toTitleCase(ch$difficulty[[1L]])," Lock"),p("Sleight of Hand: ",strong(profile$rank),if(length(profile$cards))paste0(" · ",paste(tools::toTitleCase(gsub("_"," ",profile$cards)),collapse=", "))else""),if(nzchar(profile$wild_note))p(class="confirm-note",profile$wild_note),div(class="drachuri-lock",style="--pick-angle:0deg",id=session$ns("lock_face")),sliderInput(session$ns("pick_angle"),"Position the lockpick",min=-90,max=90,value=0,step=1),div(class="lock-turn",style=paste0("--turn:",f$turn%||%0,"%"),span()),p(class="confirm-note",f$message%||%"Feel for resistance, then apply pressure."),actionButton(session$ns("turn_lock"),"Apply Pressure",class="btn btn-warning"),tags$script(HTML(sprintf("$('#%s').on('input',function(){document.getElementById('%s').style.setProperty('--pick-angle',this.value+'deg')})",session$ns("pick_angle"),session$ns("lock_face"))))))};items<-b$items;tagList(h3("Chest Opened"),p("Contents are shared: once somebody takes an item, it is gone for everyone."),if(!nrow(items))tags$em("The chest is empty.")else div(class="chest-loot-grid",lapply(seq_len(nrow(items)),function(i){item<-enemy_db_json(items$item_json[[i]],list());div(class="chest-loot",h4(item$name%||%"Item"),p(item$desc%||%""),p("Available: ",items$quantity[[i]]),tags$button(type="button",class="btn btn-success",onclick=sprintf("Shiny.setInputValue('%s',%d,{priority:'event'})",session$ns("take_item"),as.integer(items$id[[i]])),"Take"))})))})
  observeEvent(input$turn_lock,{id<-active();if(is.na(id))return();b<-get_chest_bundle(id);if(is.null(b))return();p<-sleight_profile();base<-c(easy=34,standard=22,hard=13,master=7)[[as.character(b$chest$difficulty[[1L]])]];tolerance<-max(3,base+p$tolerance_bonus);res<-chest_lockpick_attempt(id,cid(),as.numeric(input$pick_angle%||%0),tolerance,tolerance*2+p$feedback_bonus);if(!is.null(attr(res,"error"))){feedback(list(turn=0,message=attr(res,"error")));return(showNotification(attr(res,"error"),type="error"))};if(!is.null(res$character))state$char<-res$character;feedback(res);rev(rev()+1L);if(isTRUE(res$broken))showNotification(if(!is.na(res$picks_remaining%||%NA_integer_))paste0("A pick snaps; ",res$picks_remaining," remain in your thieves' tools.")else"The loose lockpick snaps.",type="error")else if(isTRUE(res$open))showNotification("The lock opens!",type="message")},ignoreInit=TRUE)
  observeEvent(input$take_item,{res<-take_chest_item(active(),as.integer(input$take_item),cid());if(!is.null(attr(res,"error")))return(showNotification(attr(res,"error"),type="error"));state$char<-res$character;rev(rev()+1L);if(isTRUE(res$chest_empty)){session$userData$pending_chest_id<-NULL;active(NA_integer_);removeModal();showNotification(paste(res$item_name,"added. The empty chest has been cleared away."),type="message")}else showNotification(paste(res$item_name,"added to your inventory."))},ignoreInit=TRUE)
  observeEvent(input$open,{rows<-invitations();if(!nrow(rows))return(showNotification("No chest is currently available to you."));choices<-setNames(as.character(rows$chest_id),paste0(rows$name," · ",ifelse(rows$locked,tools::toTitleCase(rows$difficulty),"Open")));if(length(choices)==1)return(open_chest(unname(choices[[1L]])));showModal(modalDialog(title="Available Chests",selectInput(session$ns("choice"),"Chest",choices=choices),footer=tagList(modalButton("Cancel"),actionButton(session$ns("choose"),"Inspect",class="btn btn-primary"))))},ignoreInit=TRUE)
  observeEvent(input$choose,{removeModal();open_chest(input$choice)},ignoreInit=TRUE)
  observeEvent(input$leave,{session$userData$pending_chest_id<-NULL;active(NA_integer_);removeModal()},ignoreInit=TRUE)
  observe({req(nzchar(cid()),!isTRUE(state$offline_mode),is.null(session$userData$pending_chest_id),is.null(session$userData$pending_merchant_id),is.null(session$userData$pending_note_id),is.null(session$userData$pending_opportunity));fresh<-invitations();fresh<-fresh[fresh$status=="pending"&!fresh$chest_id%in%prompted(),,drop=FALSE];req(nrow(fresh));row<-fresh[1,,drop=FALSE];id<-as.integer(row$chest_id[[1L]]);bundle<-get_chest_bundle(id);req(!is.null(bundle));ch<-bundle$chest;name<-as.character(ch$name[[1L]]%||%"Unknown Chest");if(is.na(name)||!nzchar(trimws(name)))name<-"Unknown Chest";prompted(unique(c(prompted(),id)));session$userData$pending_chest_id<-id;showModal(modalDialog(title="A chest has been discovered",p(strong(name)," is ",if(isTRUE(ch$locked[[1L]]))paste0("secured by a ",ch$difficulty[[1L]]," lock.")else"unlocked."),footer=tagList(actionButton(session$ns("dismiss"),"Leave it"),actionButton(session$ns("accept"),"Inspect Chest",class="btn btn-primary"))))})
  observeEvent(input$accept,{id<-session$userData$pending_chest_id;removeModal();open_chest(id)},ignoreInit=TRUE);observeEvent(input$dismiss,{id<-session$userData$pending_chest_id;if(!is.null(id))mark_chest_invitation(id,cid(),"dismissed");session$userData$pending_chest_id<-NULL;removeModal();rev(rev()+1L)},ignoreInit=TRUE)
})}
