library(shiny)

merchantUI<-function(id){ns<-NS(id);tagList(tags$style(HTML(paste0("#",ns("wrap"),"{position:fixed;right:22px;bottom:94px;z-index:1039}#",ns("open"),"{width:58px;height:58px;border-radius:50%;font-size:24px;background:#31543b;color:#fff4cf;border:2px solid #d7b96d;box-shadow:0 5px 18px rgba(0,0,0,.35)}#",ns("badge"),"{position:absolute;right:-3px;top:-5px;background:#8f241d;color:white;border-radius:999px;min-width:22px;padding:2px 6px;text-align:center;font-weight:bold}"))),div(id=ns("wrap"),actionButton(ns("open"),"⚖",title="Merchants"),uiOutput(ns("badge"))))}

merchantServer<-function(id,state){moduleServer(id,function(input,output,session){`%||%`<-get("%||%",inherits=TRUE);poll<-reactiveTimer(3000,session);rev<-reactiveVal(0L);prompted<-reactiveVal(integer());active_id<-reactiveVal(NA_integer_)
  cid<-reactive({x<-state$char_id;if(is.null(x)||!length(x)||is.na(x[[1]]))""else as.character(x[[1]])})
  invitations<-reactive({poll();rev();if(!nzchar(cid())||isTRUE(state$offline_mode))return(data.frame());get_pending_merchant_invitations(cid(),FALSE)})
  output$badge<-renderUI({n<-sum(invitations()$status=="pending");if(n>0)span(n)})
  merchant_choices<-function(){x<-invitations();if(!nrow(x))character()else setNames(as.character(x$merchant_id),paste0(x$name," · ",tools::toTitleCase(x$specialty)))}
  open_shop<-function(mid){mid<-suppressWarnings(as.integer(mid));bundle<-get_merchant_bundle(mid);if(is.null(bundle))return(showNotification("That merchant is no longer available.",type="warning"));active_id(mid);mark_merchant_invitation(mid,cid(),"opened");session$userData$pending_merchant_id<-mid;rev(rev()+1L);showModal(modalDialog(size="l",title=paste0(bundle$merchant$name[[1L]]," — ",tools::toTitleCase(bundle$merchant$specialty[[1L]])," merchant"),uiOutput(session$ns("shop_body")),footer=tagList(actionButton(session$ns("leave_shop"),"Leave merchant",class="btn btn-default"))))}
  output$shop_body<-renderUI({rev();mid<-active_id();if(is.na(mid))return(NULL);b<-get_merchant_bundle(mid);if(is.null(b))return(p("Merchant closed."));m<-b$merchant;s<-b$stock;stock_choices<-if(nrow(s))setNames(as.character(s$id),vapply(seq_len(nrow(s)),function(i){item<-enemy_db_json(s$item_json[[i]],list());paste0(item$name%||%"Item"," · ",s$base_value[[i]],"g base · qty ",s$quantity[[i]])},character(1)))else character();char<-validate_character(state$char);inv<-inventory_normalize(char$inventory$items);if(nrow(inv))inv<-inv[!as.logical(inv$equipped%||%FALSE),,drop=FALSE];sell_choices<-if(nrow(inv))setNames(inv$id,paste0(inv$name," · ",inv$value,"g base · qty ",inv$qty))else character();tagList(p(strong(tools::toTitleCase(m$temperament[[1L]]))," haggler · Merchant purse: ",m$gold[[1L]],"g · Your purse: ",char$inventory$gold%||%0,"g"),p("Each purchase or sale rolls Persuasion. Success improves the price; failure favours the merchant."),fluidRow(column(6,h4("Buy"),selectInput(session$ns("buy_stock"),"Stock",choices=stock_choices),actionButton(session$ns("buy"),"Haggle and Buy",class="btn btn-success")),column(6,h4("Sell"),selectInput(session$ns("sell_item"),"Your item",choices=sell_choices),actionButton(session$ns("sell"),"Haggle and Sell",class="btn btn-primary"))))})
  resolve_trade<-function(direction){mid<-active_id();target<-if(direction=="buy")input$buy_stock else input$sell_item;if(is.na(mid)||is.null(target)||!nzchar(as.character(target)))return(showNotification("Choose an item first.",type="warning"));res<-merchant_trade(mid,cid(),direction,stock_id=if(direction=="buy")target else NULL,player_item_id=if(direction=="sell")target else NULL);if(is.null(res)){msg<-attr(res,"error")%||%"The trade could not be completed.";return(showNotification(msg,type="error",duration=8))};state$char<-res$character;rev(rev()+1L);t<-res$terms;showNotification(paste0(if(t$success)"Haggling succeeded"else"Haggling failed"," (",t$roll," vs DC ",t$dc,"). ",if(direction=="buy")"Paid "else"Received ",t$price," gold for ",res$item_name,"."),type=if(t$success)"message"else"warning",duration=10)}
  observeEvent(input$buy,resolve_trade("buy"),ignoreInit=TRUE);observeEvent(input$sell,resolve_trade("sell"),ignoreInit=TRUE)
  observeEvent(input$leave_shop,{session$userData$pending_merchant_id<-NULL;removeModal()},ignoreInit=TRUE)
  observeEvent(input$open,{choices<-merchant_choices();if(!length(choices))return(showNotification("No merchant is currently trading with you.",type="message"));if(length(choices)==1)return(open_shop(unname(choices[[1L]])));showModal(modalDialog(title="Available merchants",selectInput(session$ns("merchant_choice"),"Merchant",choices=choices),footer=tagList(modalButton("Cancel"),actionButton(session$ns("choose_merchant"),"Visit",class="btn btn-success"))))},ignoreInit=TRUE)
  observeEvent(input$choose_merchant,{removeModal();open_shop(input$merchant_choice)},ignoreInit=TRUE)
  observe({invalidateLater(3000,session);if(!nzchar(cid())||isTRUE(state$offline_mode)||!is.null(session$userData$pending_merchant_id)||!is.null(session$userData$pending_trade_id)||!is.null(session$userData$pending_note_id)||!is.null(session$userData$pending_opportunity))return();fresh<-get_pending_merchant_invitations(cid(),TRUE);fresh<-fresh[!fresh$merchant_id%in%prompted(),,drop=FALSE];if(!nrow(fresh))return();r<-fresh[1,,drop=FALSE];prompted(unique(c(prompted(),r$merchant_id)));session$userData$pending_merchant_id<-as.integer(r$merchant_id[[1L]]);showModal(modalDialog(title=paste0(r$name[[1L]]," would like to trade"),p("A ",r$wealth_class[[1L]]," ",r$specialty[[1L]]," merchant with a ",r$temperament[[1L]]," haggling style has opened their wares."),footer=tagList(actionButton(session$ns("dismiss_invite"),"Not now"),actionButton(session$ns("accept_invite"),"View wares",class="btn btn-success"))))})
  observeEvent(input$accept_invite,{mid<-session$userData$pending_merchant_id;removeModal();open_shop(mid)},ignoreInit=TRUE)
  observeEvent(input$dismiss_invite,{session$userData$pending_merchant_id<-NULL;removeModal();rev(rev()+1L)},ignoreInit=TRUE)
})}
