library(shiny)

privateNotesUI <- function(id){ns<-NS(id);tagList(tags$style(HTML(paste0(
  "#",ns("note_button_wrap"),"{position:fixed;right:22px;bottom:22px;z-index:1040}",
  "#",ns("open_notes"),"{width:58px;height:58px;border-radius:50%;font-size:25px;background:#6b4b27;color:#fff4cf;border:2px solid #d7b96d;box-shadow:0 5px 18px rgba(0,0,0,.35)}",
  "#",ns("note_badge"),"{position:absolute;right:-3px;top:-5px;background:#8f241d;color:white;border-radius:999px;min-width:22px;padding:2px 6px;text-align:center;font-weight:bold}"
))),div(id=ns("note_button_wrap"),actionButton(ns("open_notes"),"✉",title="Private notes"),uiOutput(ns("note_badge"))))}

privateNotesServer <- function(id,state){moduleServer(id,function(input,output,session){
  `%||%`<-get("%||%",inherits=TRUE);prompted<-reactiveVal(integer());notes_key<-reactiveVal(0L);active_note<-reactiveVal(NULL);note_poll<-reactiveTimer(3000,session)
  cid<-reactive({x<-state$char_id;if(is.null(x)||!length(x)||is.na(x[[1]]))"" else as.character(x[[1]])});sid<-reactive(suppressWarnings(as.integer(state$active_session_id%||%NA)))
  unread<-reactive({note_poll();notes_key();if(!nzchar(cid())||isTRUE(state$offline_mode))return(data.frame());get_private_notes(cid(),TRUE)})
  output$note_badge<-renderUI({n<-nrow(unread());if(n>0)span(n)})
  compose_note<-function(recipient="",reply_to=NULL){players<-get_session_players(sid());players<-players[as.character(players$character_id)!=cid(),,drop=FALSE];if(!nrow(players)){showNotification("No other players are in this session.",type="warning");return()};session$userData$note_reply_to<-reply_to
    showModal(modalDialog(title="Write a private note",selectInput(session$ns("note_recipient"),"To",choices=setNames(as.character(players$character_id),as.character(players$char_name)),selected=recipient),textAreaInput(session$ns("note_body"),"Message",rows=8,placeholder="Write your message on the parchment…"),p("This note is delivered only to the selected player."),footer=tagList(modalButton("Cancel"),actionButton(session$ns("send_note"),"Seal and send",class="btn btn-success"))))}
  show_inbox<-function(){all<-get_private_notes(cid(),FALSE);if(!nrow(all)){compose_note();return()};labels<-paste0(ifelse(all$status=="sent","✉ ","✓ "),all$sender_name," · ",format(as.POSIXct(all$created_at),"%d %b %H:%M"));showModal(modalDialog(title="Private notes",selectInput(session$ns("inbox_note_id"),"Received notes",choices=setNames(as.character(all$id),labels)),footer=tagList(modalButton("Close"),actionButton(session$ns("compose_note"),"Write note"),actionButton(session$ns("open_inbox_note"),"Open selected",class="btn btn-primary"))))}
  open_note<-function(id){all<-get_private_notes(cid(),FALSE);row<-all[all$id==as.integer(id),,drop=FALSE];if(!nrow(row))return();mark_private_note(id,cid(),"read");notes_key(notes_key()+1L);active_note(row);session$userData$pending_note_id<-as.integer(id);showModal(modalDialog(title=paste0("A note from ",row$sender_name[[1]]),div(style="background:#fff8dc;border:1px solid #c7a96b;padding:18px;font-family:Georgia,serif;white-space:pre-wrap",row$body[[1]]),footer=tagList(actionButton(session$ns("ack_note"),"Acknowledge",class="btn btn-default"),actionButton(session$ns("reply_note"),"Reply",class="btn btn-primary"))))}
  observeEvent(input$open_notes,show_inbox(),ignoreInit=TRUE);observeEvent(input$compose_note,compose_note(),ignoreInit=TRUE);observeEvent(input$open_inbox_note,open_note(input$inbox_note_id),ignoreInit=TRUE)
  observeEvent(input$send_note,{id<-send_private_note(sid(),cid(),input$note_recipient,input$note_body,session$userData$note_reply_to);if(is.null(id)){showNotification("Write a note before sending.",type="error");return()};session$userData$note_reply_to<-NULL;removeModal();showNotification("Your sealed note was delivered.",type="message")},ignoreInit=TRUE)
  observeEvent(input$ack_note,{row<-active_note();if(!is.null(row))mark_private_note(row$id[[1]],cid(),"acknowledged");session$userData$pending_note_id<-NULL;active_note(NULL);removeModal();notes_key(notes_key()+1L)},ignoreInit=TRUE)
  observeEvent(input$reply_note,{row<-active_note();if(is.null(row))return();mark_private_note(row$id[[1]],cid(),"acknowledged");session$userData$pending_note_id<-NULL;active_note(NULL);notes_key(notes_key()+1L);compose_note(as.character(row$sender_character_id[[1]]),as.integer(row$id[[1]]))},ignoreInit=TRUE)
  observe({invalidateLater(3000,session);if(!nzchar(cid())||isTRUE(state$offline_mode)||!is.null(session$userData$pending_merchant_id)||!is.null(session$userData$pending_trade_id)||!is.null(session$userData$pending_note_id)||!is.null(session$userData$pending_opportunity))return();fresh<-unread();fresh<-fresh[!fresh$id%in%prompted(),,drop=FALSE];if(!nrow(fresh))return();row<-fresh[nrow(fresh),,drop=FALSE];prompted(unique(c(prompted(),row$id)));session$userData$pending_note_id<-as.integer(row$id[[1]]);active_note(row);showModal(modalDialog(title=paste0(row$sender_name[[1]]," passed you a note"),p("Open and read it?"),footer=tagList(actionButton(session$ns("note_later"),"Later"),actionButton(session$ns("open_prompted_note"),"Open note",class="btn btn-primary"))))})
  observeEvent(input$open_prompted_note,{row<-active_note();session$userData$pending_note_id<-NULL;if(!is.null(row))open_note(row$id[[1]])},ignoreInit=TRUE)
  observeEvent(input$note_later,{session$userData$pending_note_id<-NULL;active_note(NULL);removeModal()},ignoreInit=TRUE)
})}
