runeCraftingUI <- function(id) {
  ns<-NS(id)
  tagList(tags$style(HTML(paste0("#",ns("root")," .glyph-card{border:1px solid rgba(119,84,150,.45);border-radius:14px;background:rgba(255,252,245,.94);padding:14px;margin-bottom:12px}#",ns("root")," .glyph-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:12px}#",ns("root")," .glyph-pills{display:flex;gap:6px;flex-wrap:wrap}#",ns("root")," .glyph-pill{padding:4px 8px;border-radius:999px;background:#eee3f3;font-size:12px}#",ns("root")," .glyph-effect{white-space:pre-wrap;margin-top:8px}"))),
    div(id=ns("root"),div(class="glyph-grid",
      div(class="glyph-card",h3("✧ Glyph Workshop"),p("Craft persistent runes, wards, and enhancements outside combat. Names and descriptions are generated from the selected rules."),fluidRow(column(6,selectInput(ns("glyph_type"),"Glyph type",c("Rune"="rune","Ward"="ward","Enhancement"="enhancement"))),column(6,uiOutput(ns("rank_ui")))),uiOutput(ns("type_fields")),actionButton(ns("review_project"),"Review & Start Project",class="btn btn-primary")),
      div(class="glyph-card",h3("Crafting Rule"),uiOutput(ns("character_magic_summary")),uiOutput(ns("rule_summary")))
    ),div(class="glyph-card",h3("Your Glyphs & Projects"),uiOutput(ns("glyphs_ui")),tags$hr(),fluidRow(column(5,selectInput(ns("active_glyph_id"),"Project needing crafting time",choices=character())),column(3,numericInput(ns("work_hours"),"Hours to apply",1,min=.25,step=.25)),column(4,br(),actionButton(ns("work_project"),"Apply Crafting Time",class="btn btn-primary"))),uiOutput(ns("selected_project_summary")),tags$hr(),h4("Weapon Enhancements"),fluidRow(column(8,selectInput(ns("replenish_weapon_id"),"Enchanted weapon",choices=character())),column(4,br(),actionButton(ns("replenish_weapon"),"Replenish",class="btn btn-warning")))))
  )
}

runeCraftingServer <- function(id,state,char_rev,bump_char_rev=NULL) {
  moduleServer(id,function(input,output,session){
    `%||%`<-get("%||%",inherits=TRUE);refresh<-reactiveVal(0L)
    cid<-reactive({x<-state$char_id;if(is.null(x)||!length(x)||is.na(x[[1L]]))""else as.character(x[[1L]])})
    in_combat<-reactive({eid<-suppressWarnings(as.integer(state$active_encounter_id%||%NA));if(is.na(eid))return(FALSE);x<-get_combat_state(eid);is.data.frame(x)&&nrow(x)&&identical(as.character(x$phase[[1L]]%||%""),"combat")})
    current_char<-reactive({char_rev();validate_character(state$char)});unlocked<-reactive(glyph_unlocked_ranks(current_char()))
    output$rank_ui<-renderUI(selectInput(session$ns("rank"),"Rank",choices=unlocked()))
    inventory_choices<-reactive({inv<-inventory_normalize(current_char()$inventory$items);inv<-inv[inv$type=="weapon",,drop=FALSE];if(!nrow(inv))character()else setNames(inv$id,paste0(inv$name," · ",vapply(inv$meta,function(m)paste0(m$damage1%||%"?"," ",m$dmg_type1%||%"damage"),character(1))))})
    output$type_fields<-renderUI({req(input$glyph_type,input$rank);type<-input$glyph_type;rank<-input$rank;if(type=="rune")return(tagList(selectInput(session$ns("material"),"Rune blank",choices=get_available_rune_materials(rank)),selectInput(session$ns("damage_type"),"Released magical damage",choices=GLYPH_DAMAGE_TYPES),tags$small("Once completed, the rune is placed in Inventory and becomes available in combat.")));if(type=="ward"){rule<-WARD_RULES[[rank]];return(tagList(selectInput(session$ns("material"),"Ward material (one is consumed)",choices=rule$materials),numericInput(session$ns("size_ft"),paste0("Ward size in feet (minimum ",rule$min_size_ft,"ft)"),rule$min_size_ft,min=rule$min_size_ft,step=1)))};tagList(selectInput(session$ns("damage_type"),"Extra magical damage type",choices=GLYPH_DAMAGE_TYPES),numericInput(session$ns("enhancement_days"),"Active duration in campaign days",1,min=1,max=365),selectInput(session$ns("target_item"),"Weapon to enhance",choices=inventory_choices()))})
    preview_rule<-reactive({req(input$glyph_type,input$rank);get_glyph_rule(input$glyph_type,input$rank,glyph_arcana_bonus(current_char()),input$material,input$size_ft,input$enhancement_days)})
    output$character_magic_summary<-renderUI({
      x<-current_char()
      tagList(
        div(class="glyph-pills",
          span(class="glyph-pill",paste("Character level",glyph_character_level(x))),
          span(class="glyph-pill",paste("Glyph level",glyph_mastery_level(x),"of 4")),
          span(class="glyph-pill",paste("Arcana",sprintf("%+d",glyph_arcana_bonus(x)))),
          span(class="glyph-pill",paste("Sindre",x$resources$sindre$cur%||%0)),
          span(class="glyph-pill",paste("HP",x$resources$hp$cur%||%0))
        ),
        p("Available ranks: ",paste(unlocked(),collapse=", "))
      )
    })
    output$rule_summary<-renderUI({
      r<-preview_rule();req(r);type<-tolower(input$glyph_type);target_label<-names(inventory_choices())[match(input$target_item%||%"",unname(inventory_choices()))];if(!length(target_label)||is.na(target_label))target_label<-"Choose a weapon"
      item<-function(label,value)tags$li(tags$strong(paste0(label,": ")),value)
      items<-if(type=="rune")list(item("Material",r$required_blank),item("Released damage",paste(unname(RUNE_DAMAGE_BY_RANK[[input$rank]]),input$damage_type%||%"Fire","in a",paste0(unname(RUNE_RADIUS_BY_RANK[[input$rank]]),"ft area"))),item("Tool",r$required_tools),item("Crafting time",paste(r$crafting_time,"hours (rolled when started)")),item("Cost",paste(r$cost,"(rolled when started)")),item("Active",paste(r$active_time_rounds,"round(s)")),item("Arcane Score",r$arcane_score),item("Instability",paste("Natural 1 in combat;",r$instability_damage,"damage within",paste0(r$instability_radius_ft,"ft"))),item("Use",r$usage),item("Counters",paste(r$counter_dodge,r$counter_disrupt,sep="; ")))else if(type=="ward")list(item("Material",r$material),item("Size",paste0(r$size_ft,"ft")),item("Crafting time",paste(r$crafting_hours,"hours")),item("Cost",r$cost),item("Arcane Score",r$arcane_score),item("Duration",r$active_time),item("Counter",r$counter))else list(item("Target weapon",target_label),item("Extra damage",paste(r$damage,input$damage_type%||%"Fire")),item("Crafting time",paste(r$crafting_hours,"hours")),item("Cost",r$cost),item("Arcane Score",r$arcane_score),item("Active",r$active_time),item("Replenishment",r$replenishment),item("Counter",r$counter));tags$ul(items)
    })
    glyphs<-reactive({refresh();char_rev();if(!nzchar(cid())||isTRUE(state$offline_mode))return(data.frame());get_character_glyphs(cid())})
    observe({g<-glyphs();g<-g[g$status=="crafting",,drop=FALSE];choices<-if(nrow(g))setNames(as.character(g$id),paste0(g$name," · ",round(g$crafting_hours_completed,2),"/",round(g$crafting_hours_required,2),"h · ",round(pmax(0,g$crafting_hours_required-g$crafting_hours_completed),2),"h remaining"))else character();keep<-isolate(input$active_glyph_id%||%"");updateSelectInput(session,"active_glyph_id",choices=choices,selected=if(keep%in%unname(choices))keep else if(length(choices))unname(choices[[1L]])else character())})
    output$selected_project_summary<-renderUI({g<-glyphs();id<-suppressWarnings(as.integer(input$active_glyph_id));x<-g[g$id==id&g$status=="crafting",,drop=FALSE];if(!nrow(x))return(tags$small("No unfinished crafting projects."));remaining<-max(0,as.numeric(x$crafting_hours_required[[1L]])-as.numeric(x$crafting_hours_completed[[1L]]));tags$p(style="margin-top:8px",tags$strong(x$name[[1L]]),": requires ",round(x$crafting_hours_required[[1L]],2)," total hours; ",tags$strong(round(remaining,2)," hours remain."))})
    observe({refresh();char_rev();w<-replenishable_weapon_choices(current_char());day<-as.integer(current_char()$meta$day%||%1L);choices<-if(nrow(w))setNames(w$id,vapply(seq_len(nrow(w)),function(i){m<-w$meta[[i]];paste0(w$name[[i]]," · +",m$glyph_damage," ",m$glyph_damage_type," · ",if(day<=as.integer(m$glyph_active_until_day%||%NA))paste("active through day",m$glyph_active_until_day)else"DEPLETED")},character(1)))else character();updateSelectInput(session,"replenish_weapon_id",choices=choices)})
    output$glyphs_ui<-renderUI({g<-glyphs();if(!nrow(g))return(tags$em("No glyphs or crafting projects yet."));day<-as.integer(current_char()$meta$day%||%1L);div(class="glyph-grid",lapply(seq_len(nrow(g)),function(i){x<-g[i,,drop=FALSE];status<-as.character(x$status[[1L]]);if(x$glyph_type[[1L]]=="enhancement"&&status=="active"&&!is.na(x$active_until_day[[1L]])&&day>x$active_until_day[[1L]])status<-"depleted";progress<-paste0(round(as.numeric(x$crafting_hours_completed[[1L]]),2),"/",round(as.numeric(x$crafting_hours_required[[1L]]),2)," hours");pills<-c(paste(tools::toTitleCase(x$glyph_type[[1L]]),x$rank[[1L]]),paste("Status",status),paste("Arcane Score",x$arcane_score[[1L]]),if(x$status[[1L]]=="crafting")progress else NULL,if(!is.na(x$material[[1L]]))as.character(x$material[[1L]])else NULL,if(!is.na(x$size_ft[[1L]]))paste0(x$size_ft[[1L]],"ft")else NULL,if(!is.na(x$active_until_day[[1L]]))paste("Active through day",x$active_until_day[[1L]])else NULL);div(class="glyph-card",h4(x$name[[1L]]),div(class="glyph-pills",lapply(pills,function(p)span(class="glyph-pill",p))),div(class="glyph-effect",x$effect_description[[1L]]),if(!is.na(x$instability_damage[[1L]]))p("Instability: ",x$instability_damage[[1L]]," in ",x$instability_radius_ft[[1L]],"ft")else NULL)}))})
    refresh_character<-function(char,consumed_material=""){current<-validate_character(state$char);fresh<-validate_character(char);current$resources<-fresh$resources;old<-inventory_normalize(current$inventory$items);new<-inventory_normalize(fresh$inventory$items);for(i in seq_len(nrow(new))){idx<-match(new$id[[i]],old$id);if(is.na(idx))old<-rbind(old,new[i,,drop=FALSE])else old[idx,]<-new[i,]};if(nzchar(consumed_material)){idx<-glyph_inventory_index(old,consumed_material);if(!is.na(idx)){if(old$qty[[idx]]>1)old$qty[[idx]]<-old$qty[[idx]]-1 else old<-old[-idx,,drop=FALSE]}};current$inventory$items<-inventory_normalize(old);current$inventory$gold<-fresh$inventory$gold;state$char<-validate_character(current);if(is.function(bump_char_rev))bump_char_rev();refresh(refresh()+1L)}
    observeEvent(cid(),{if(!nzchar(cid())||isTRUE(state$offline_mode))return();fixed<-sync_active_weapon_enhancements(cid());if(!is.null(fixed))refresh_character(fixed)},ignoreInit=FALSE,once=TRUE)
    observeEvent(input$review_project,{if(in_combat())return(showNotification("Glyphs must be crafted outside combat.",type="warning"));r<-preview_rule();req(r);identity<-glyph_default_identity(input$glyph_type,input$rank,input$damage_type,input$material,names(inventory_choices())[match(input$target_item%||%"",unname(inventory_choices()))]);showModal(modalDialog(title="Start glyph project?",p(strong(identity$name)),p(identity$description),p("Starting consumes the required material and immediately rolls and pays the listed Sindre or HP cost. Crafting time is then tracked as an in-game project."),footer=tagList(modalButton("Cancel"),actionButton(session$ns("confirm_project"),"Consume materials & start",class="btn btn-danger"))))},ignoreInit=TRUE)
    observeEvent(input$confirm_project,{removeModal();res<-start_glyph_project(cid(),input$glyph_type,input$rank,"","",input$material,input$size_ft,input$enhancement_days,input$target_item,input$damage_type);if(length(res$error%||%character()))return(showNotification(res$error,type="error",duration=10));refresh_character(res$character,res$consumed_material%||%"");showNotification(paste0("Project started: ",res$glyph$name[[1L]],". Paid ",res$cost," ",toupper(res$resource),"."),type="message",duration=10)},ignoreInit=TRUE)
    observeEvent(input$work_project,{if(in_combat())return(showNotification("Crafting time cannot be applied during combat.",type="warning"));id<-suppressWarnings(as.integer(input$active_glyph_id));if(is.na(id))return();res<-work_glyph_project(cid(),id,input$work_hours);if(is.null(res))return(showNotification("Crafting time could not be recorded.",type="error"));if(!is.null(res$character))refresh_character(res$character)else refresh(refresh()+1L);showNotification(if(res$glyph$status[[1L]]=="crafting")"Crafting progress recorded."else"Glyph completed and added to Inventory.",type="message")},ignoreInit=TRUE)
    observeEvent(input$replenish_weapon,{req(input$replenish_weapon_id);quote<-tryCatch(weapon_enchantment_quote(current_char(),input$replenish_weapon_id),error=function(e)structure(list(),error=e$message));if(length(quote$error%||%character()))return(showNotification(quote$error,type="error"));session$userData$glyph_replenish_quote<-quote;showModal(modalDialog(title=paste("Replenish",quote$weapon_name,"?"),p(strong(quote$rank," enhancement")," · +",quote$damage," ",quote$damage_type),p("Duration: ",strong(quote$days," campaign day(s)")),p("Cost rule: ",quote$days," × ",quote$dice," Sindre"),p("This replenishment rolled ",strong(quote$cost," Sindre"),". You currently have ",quote$current_sindre,"."),footer=tagList(modalButton("Cancel"),actionButton(session$ns("confirm_replenish_weapon"),paste0("Pay ",quote$cost," Sindre"),class="btn btn-warning"))))},ignoreInit=TRUE)
    observeEvent(input$confirm_replenish_weapon,{quote<-session$userData$glyph_replenish_quote;if(is.null(quote))return();res<-replenish_weapon_enchantment(cid(),quote$weapon_id,quote$cost);if(length(res$error%||%character()))return(showNotification(res$error,type="error"));session$userData$glyph_replenish_quote<-NULL;removeModal();refresh_character(res$character);showNotification(paste0(res$weapon_name," replenished through day ",res$active_until_day," for ",res$cost," Sindre."),type="message")},ignoreInit=TRUE)
  })
}
